// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_promotion/voucher_user.proto

package service_promotion

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PromotionUser struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdVoucher            string   `protobuf:"bytes,2,opt,name=idVoucher,proto3" json:"idVoucher,omitempty"`
	IdUser               string   `protobuf:"bytes,3,opt,name=idUser,proto3" json:"idUser,omitempty"`
	Amount               int64    `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Total                int64    `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	TotalFreeze          int64    `protobuf:"varint,6,opt,name=totalFreeze,proto3" json:"totalFreeze,omitempty"`
	FreezeIds            []string `protobuf:"bytes,7,rep,name=freezeIds,proto3" json:"freezeIds,omitempty"`
	Code                 string   `protobuf:"bytes,8,opt,name=code,proto3" json:"code,omitempty"`
	Status               string   `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            int64    `protobuf:"varint,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	LastUsed             int64    `protobuf:"varint,11,opt,name=lastUsed,proto3" json:"lastUsed,omitempty"`
	LastBuy              int64    `protobuf:"varint,12,opt,name=lastBuy,proto3" json:"lastBuy,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,13,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	V                    int64    `protobuf:"varint,14,opt,name=v,proto3" json:"v,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PromotionUser) Reset()         { *m = PromotionUser{} }
func (m *PromotionUser) String() string { return proto.CompactTextString(m) }
func (*PromotionUser) ProtoMessage()    {}
func (*PromotionUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_voucher_user_ee9651542366a9f7, []int{0}
}
func (m *PromotionUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromotionUser.Unmarshal(m, b)
}
func (m *PromotionUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromotionUser.Marshal(b, m, deterministic)
}
func (dst *PromotionUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromotionUser.Merge(dst, src)
}
func (m *PromotionUser) XXX_Size() int {
	return xxx_messageInfo_PromotionUser.Size(m)
}
func (m *PromotionUser) XXX_DiscardUnknown() {
	xxx_messageInfo_PromotionUser.DiscardUnknown(m)
}

var xxx_messageInfo_PromotionUser proto.InternalMessageInfo

func (m *PromotionUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PromotionUser) GetIdVoucher() string {
	if m != nil {
		return m.IdVoucher
	}
	return ""
}

func (m *PromotionUser) GetIdUser() string {
	if m != nil {
		return m.IdUser
	}
	return ""
}

func (m *PromotionUser) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PromotionUser) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PromotionUser) GetTotalFreeze() int64 {
	if m != nil {
		return m.TotalFreeze
	}
	return 0
}

func (m *PromotionUser) GetFreezeIds() []string {
	if m != nil {
		return m.FreezeIds
	}
	return nil
}

func (m *PromotionUser) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *PromotionUser) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PromotionUser) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *PromotionUser) GetLastUsed() int64 {
	if m != nil {
		return m.LastUsed
	}
	return 0
}

func (m *PromotionUser) GetLastBuy() int64 {
	if m != nil {
		return m.LastBuy
	}
	return 0
}

func (m *PromotionUser) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *PromotionUser) GetV() int64 {
	if m != nil {
		return m.V
	}
	return 0
}

type PromotionUserApply struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PromoID              string   `protobuf:"bytes,2,opt,name=promoID,proto3" json:"promoID,omitempty"`
	UserID               string   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	Status               int64    `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	StartDate            int64    `protobuf:"varint,5,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate              int64    `protobuf:"varint,6,opt,name=endDate,proto3" json:"endDate,omitempty"`
	V                    int64    `protobuf:"varint,7,opt,name=v,proto3" json:"v,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PromotionUserApply) Reset()         { *m = PromotionUserApply{} }
func (m *PromotionUserApply) String() string { return proto.CompactTextString(m) }
func (*PromotionUserApply) ProtoMessage()    {}
func (*PromotionUserApply) Descriptor() ([]byte, []int) {
	return fileDescriptor_voucher_user_ee9651542366a9f7, []int{1}
}
func (m *PromotionUserApply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromotionUserApply.Unmarshal(m, b)
}
func (m *PromotionUserApply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromotionUserApply.Marshal(b, m, deterministic)
}
func (dst *PromotionUserApply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromotionUserApply.Merge(dst, src)
}
func (m *PromotionUserApply) XXX_Size() int {
	return xxx_messageInfo_PromotionUserApply.Size(m)
}
func (m *PromotionUserApply) XXX_DiscardUnknown() {
	xxx_messageInfo_PromotionUserApply.DiscardUnknown(m)
}

var xxx_messageInfo_PromotionUserApply proto.InternalMessageInfo

func (m *PromotionUserApply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PromotionUserApply) GetPromoID() string {
	if m != nil {
		return m.PromoID
	}
	return ""
}

func (m *PromotionUserApply) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *PromotionUserApply) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PromotionUserApply) GetStartDate() int64 {
	if m != nil {
		return m.StartDate
	}
	return 0
}

func (m *PromotionUserApply) GetEndDate() int64 {
	if m != nil {
		return m.EndDate
	}
	return 0
}

func (m *PromotionUserApply) GetV() int64 {
	if m != nil {
		return m.V
	}
	return 0
}

type VoucherUserDetail struct {
	VoucherDetail        *VoucherDetail `protobuf:"bytes,1,opt,name=voucher_detail,json=voucherDetail,proto3" json:"voucher_detail,omitempty"`
	VoucherUser          *PromotionUser `protobuf:"bytes,2,opt,name=voucher_user,json=voucherUser,proto3" json:"voucher_user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *VoucherUserDetail) Reset()         { *m = VoucherUserDetail{} }
func (m *VoucherUserDetail) String() string { return proto.CompactTextString(m) }
func (*VoucherUserDetail) ProtoMessage()    {}
func (*VoucherUserDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_voucher_user_ee9651542366a9f7, []int{2}
}
func (m *VoucherUserDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoucherUserDetail.Unmarshal(m, b)
}
func (m *VoucherUserDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoucherUserDetail.Marshal(b, m, deterministic)
}
func (dst *VoucherUserDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoucherUserDetail.Merge(dst, src)
}
func (m *VoucherUserDetail) XXX_Size() int {
	return xxx_messageInfo_VoucherUserDetail.Size(m)
}
func (m *VoucherUserDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_VoucherUserDetail.DiscardUnknown(m)
}

var xxx_messageInfo_VoucherUserDetail proto.InternalMessageInfo

func (m *VoucherUserDetail) GetVoucherDetail() *VoucherDetail {
	if m != nil {
		return m.VoucherDetail
	}
	return nil
}

func (m *VoucherUserDetail) GetVoucherUser() *PromotionUser {
	if m != nil {
		return m.VoucherUser
	}
	return nil
}

func init() {
	proto.RegisterType((*PromotionUser)(nil), "service_promotion.PromotionUser")
	proto.RegisterType((*PromotionUserApply)(nil), "service_promotion.PromotionUserApply")
	proto.RegisterType((*VoucherUserDetail)(nil), "service_promotion.VoucherUserDetail")
}

func init() {
	proto.RegisterFile("service_promotion/voucher_user.proto", fileDescriptor_voucher_user_ee9651542366a9f7)
}

var fileDescriptor_voucher_user_ee9651542366a9f7 = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x5d, 0x8a, 0xdb, 0x30,
	0x10, 0xc6, 0xce, 0x8f, 0x93, 0x71, 0x12, 0x88, 0x28, 0x45, 0x84, 0x3e, 0x98, 0x50, 0x4a, 0x9e,
	0x52, 0x68, 0x4f, 0x90, 0xd6, 0xb4, 0xe4, 0xad, 0x18, 0xd2, 0xd7, 0xa0, 0x5a, 0x2a, 0x6b, 0x70,
	0x22, 0x23, 0xc9, 0x86, 0xec, 0x6d, 0xf6, 0x0e, 0x7b, 0xaf, 0xbd, 0xc2, 0xa2, 0x91, 0x1c, 0x3b,
	0x64, 0xf7, 0x6d, 0xbe, 0x6f, 0x34, 0xa3, 0x6f, 0xbe, 0x19, 0xf8, 0xac, 0x85, 0x6a, 0x8a, 0x5c,
	0x1c, 0x2b, 0x25, 0x4f, 0xd2, 0x14, 0xf2, 0xfc, 0xb5, 0x91, 0x75, 0xfe, 0x20, 0xd4, 0xb1, 0xd6,
	0x42, 0x6d, 0x2b, 0x25, 0x8d, 0x24, 0xcb, 0xbb, 0x57, 0xab, 0x2f, 0xef, 0x17, 0x72, 0x61, 0x58,
	0x51, 0xba, 0xd2, 0xf5, 0x4b, 0x08, 0xf3, 0x3f, 0xed, 0x93, 0x83, 0x16, 0x8a, 0x2c, 0x20, 0x2c,
	0x38, 0x0d, 0x92, 0x60, 0x33, 0xcd, 0xc2, 0x82, 0x93, 0x4f, 0x30, 0x2d, 0xf8, 0x5f, 0x57, 0x4b,
	0x43, 0xa4, 0x3b, 0x82, 0x7c, 0x84, 0x71, 0xc1, 0x6d, 0x1d, 0x1d, 0x60, 0xca, 0x23, 0xcb, 0xb3,
	0x93, 0xac, 0xcf, 0x86, 0x0e, 0x93, 0x60, 0x33, 0xc8, 0x3c, 0x22, 0x1f, 0x60, 0x64, 0xa4, 0x61,
	0x25, 0x1d, 0x21, 0xed, 0x00, 0x49, 0x20, 0xc6, 0xe0, 0x97, 0x12, 0xe2, 0x51, 0xd0, 0x31, 0xe6,
	0xfa, 0x94, 0x55, 0xf1, 0x1f, 0xa3, 0x3d, 0xd7, 0x34, 0x4a, 0x06, 0x56, 0xc5, 0x95, 0x20, 0x04,
	0x86, 0xb9, 0xe4, 0x82, 0x4e, 0x50, 0x03, 0xc6, 0x56, 0x81, 0x36, 0xcc, 0xd4, 0x9a, 0x4e, 0x9d,
	0x32, 0x87, 0x6c, 0xa7, 0x5c, 0x09, 0x66, 0x04, 0xdf, 0x19, 0x0a, 0xf8, 0x53, 0x47, 0x90, 0x15,
	0x4c, 0x4a, 0xa6, 0xcd, 0x41, 0x0b, 0x4e, 0x63, 0x4c, 0x5e, 0x31, 0xa1, 0x10, 0xd9, 0xf8, 0x47,
	0x7d, 0xa1, 0x33, 0x4c, 0xb5, 0xd0, 0xf6, 0xac, 0x2b, 0xee, 0x7b, 0xce, 0x5d, 0xcf, 0x2b, 0x41,
	0x66, 0x10, 0x34, 0x74, 0x81, 0x6c, 0xd0, 0xac, 0x9f, 0x03, 0x20, 0x37, 0x8e, 0xef, 0xaa, 0xaa,
	0xbc, 0xdc, 0xd9, 0x4e, 0x21, 0xc2, 0xd5, 0xed, 0x53, 0x6f, 0x7a, 0x0b, 0xed, 0x60, 0x76, 0xf7,
	0xfb, 0xb4, 0xb5, 0xdc, 0xa1, 0xde, 0xc0, 0xde, 0xf2, 0x6e, 0x60, 0x6d, 0x98, 0x32, 0x29, 0x33,
	0xc2, 0xdb, 0xde, 0x11, 0xf6, 0x1f, 0x71, 0xe6, 0x98, 0x73, 0xb6, 0xb7, 0xd0, 0xc9, 0x8e, 0x5a,
	0xd9, 0x4f, 0x01, 0x2c, 0xfd, 0xd2, 0xad, 0xe8, 0x14, 0x8f, 0x88, 0xfc, 0x86, 0xc5, 0xed, 0x59,
	0xe1, 0x04, 0xf1, 0xb7, 0x64, 0x7b, 0x77, 0x7f, 0x5b, 0x5f, 0xed, 0x2a, 0xb3, 0x79, 0xd3, 0x87,
	0xe4, 0x27, 0xcc, 0xfa, 0x87, 0x8d, 0x33, 0xbf, 0xdd, 0xe6, 0xc6, 0xbb, 0x2c, 0x6e, 0x3a, 0x4d,
	0xff, 0xc6, 0x78, 0xd3, 0xdf, 0x5f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x65, 0xb5, 0xf0, 0x6f, 0x36,
	0x03, 0x00, 0x00,
}
