// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	entities "orders-system/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// IDevice is an autogenerated mock type for the IDevice type
type IDevice struct {
	mock.Mock
}

// CreateDevice provides a mock function with given fields: devices
func (_m *IDevice) CreateDevice(devices entities.Devices) (*entities.Devices, error) {
	ret := _m.Called(devices)

	var r0 *entities.Devices
	if rf, ok := ret.Get(0).(func(entities.Devices) *entities.Devices); ok {
		r0 = rf(devices)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Devices)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entities.Devices) error); ok {
		r1 = rf(devices)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteDevice provides a mock function with given fields: device_id, user_id
func (_m *IDevice) DeleteDevice(device_id string, user_id string) error {
	ret := _m.Called(device_id, user_id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(device_id, user_id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindById provides a mock function with given fields: id
func (_m *IDevice) FindById(id string) (*entities.Devices, error) {
	ret := _m.Called(id)

	var r0 *entities.Devices
	if rf, ok := ret.Get(0).(func(string) *entities.Devices); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Devices)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUserId provides a mock function with given fields: user_id
func (_m *IDevice) FindByUserId(user_id string) (*entities.Devices, error) {
	ret := _m.Called(user_id)

	var r0 *entities.Devices
	if rf, ok := ret.Get(0).(func(string) *entities.Devices); ok {
		r0 = rf(user_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Devices)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(user_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDevice provides a mock function with given fields: device_id, device_token
func (_m *IDevice) UpdateDevice(device_id string, device_token string) error {
	ret := _m.Called(device_id, device_token)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(device_id, device_token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
