// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "orders-system/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

// CheckLuckyMoney provides a mock function with given fields: ctx, user_id, lucky_money_id
func (_m *OrderRepository) CheckLuckyMoney(ctx context.Context, user_id string, lucky_money_id string) (*entities.OrderEntity, error) {
	ret := _m.Called(ctx, user_id, lucky_money_id)

	var r0 *entities.OrderEntity
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entities.OrderEntity); ok {
		r0 = rf(ctx, user_id, lucky_money_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.OrderEntity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, user_id, lucky_money_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, entity
func (_m *OrderRepository) Create(ctx context.Context, entity *entities.OrderEntity) (*entities.OrderEntity, error) {
	ret := _m.Called(ctx, entity)

	var r0 *entities.OrderEntity
	if rf, ok := ret.Get(0).(func(context.Context, *entities.OrderEntity) *entities.OrderEntity); ok {
		r0 = rf(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.OrderEntity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *entities.OrderEntity) error); ok {
		r1 = rf(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, orderID
func (_m *OrderRepository) FindByID(ctx context.Context, orderID string) (*entities.OrderEntity, error) {
	ret := _m.Called(ctx, orderID)

	var r0 *entities.OrderEntity
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.OrderEntity); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.OrderEntity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByOrderID provides a mock function with given fields: ctx, orderID
func (_m *OrderRepository) FindByOrderID(ctx context.Context, orderID string) (*entities.OrderEntity, error) {
	ret := _m.Called(ctx, orderID)

	var r0 *entities.OrderEntity
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.OrderEntity); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.OrderEntity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetExpiredOrder provides a mock function with given fields: ctx
func (_m *OrderRepository) GetExpiredOrder(ctx context.Context) ([]*entities.OrderEntity, error) {
	ret := _m.Called(ctx)

	var r0 []*entities.OrderEntity
	if rf, ok := ret.Get(0).(func(context.Context) []*entities.OrderEntity); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.OrderEntity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderByRefundId provides a mock function with given fields: ctx, refundId
func (_m *OrderRepository) GetOrderByRefundId(ctx context.Context, refundId string) (*entities.OrderEntity, error) {
	ret := _m.Called(ctx, refundId)

	var r0 *entities.OrderEntity
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.OrderEntity); ok {
		r0 = rf(ctx, refundId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.OrderEntity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refundId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessingOrderByID provides a mock function with given fields: ctx, entity
func (_m *OrderRepository) ProcessingOrderByID(ctx context.Context, entity *entities.OrderEntity) (*entities.OrderEntity, error) {
	ret := _m.Called(ctx, entity)

	var r0 *entities.OrderEntity
	if rf, ok := ret.Get(0).(func(context.Context, *entities.OrderEntity) *entities.OrderEntity); ok {
		r0 = rf(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.OrderEntity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *entities.OrderEntity) error); ok {
		r1 = rf(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReplaceByID provides a mock function with given fields: ctx, entity
func (_m *OrderRepository) ReplaceByID(ctx context.Context, entity *entities.OrderEntity) (*entities.OrderEntity, error) {
	ret := _m.Called(ctx, entity)

	var r0 *entities.OrderEntity
	if rf, ok := ret.Get(0).(func(context.Context, *entities.OrderEntity) *entities.OrderEntity); ok {
		r0 = rf(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.OrderEntity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *entities.OrderEntity) error); ok {
		r1 = rf(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
