// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_user/merchant.proto

package service_user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MerchantDTO struct {
	Id                     string              `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Email                  string              `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Code                   string              `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`
	Logo                   string              `protobuf:"bytes,4,opt,name=Logo,proto3" json:"Logo,omitempty"`
	SecretKey              string              `protobuf:"bytes,5,opt,name=SecretKey,proto3" json:"SecretKey,omitempty"`
	Salt                   string              `protobuf:"bytes,6,opt,name=Salt,proto3" json:"Salt,omitempty"`
	UserID                 string              `protobuf:"bytes,7,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Address                string              `protobuf:"bytes,8,opt,name=Address,proto3" json:"Address,omitempty"`
	Limited                int64               `protobuf:"varint,9,opt,name=Limited,proto3" json:"Limited,omitempty"`
	Name                   string              `protobuf:"bytes,10,opt,name=Name,proto3" json:"Name,omitempty"`
	PhoneNumber            string              `protobuf:"bytes,11,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	ParentId               string              `protobuf:"bytes,12,opt,name=ParentId,proto3" json:"ParentId,omitempty"`
	Status                 string              `protobuf:"bytes,13,opt,name=Status,proto3" json:"Status,omitempty"`
	Website                string              `protobuf:"bytes,14,opt,name=Website,proto3" json:"Website,omitempty"`
	PaymentGatewaySettings *MerchantPaygateDTO `protobuf:"bytes,15,opt,name=payment_gateway_settings,json=paymentGatewaySettings,proto3" json:"payment_gateway_settings,omitempty"`
	BusinessTypeId         string              `protobuf:"bytes,16,opt,name=business_type_id,json=businessTypeId,proto3" json:"business_type_id,omitempty"`
	BusinessLicenseStatus  string              `protobuf:"bytes,17,opt,name=business_license_status,json=businessLicenseStatus,proto3" json:"business_license_status,omitempty"`
	PublicKey              string              `protobuf:"bytes,18,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}            `json:"-"`
	XXX_unrecognized       []byte              `json:"-"`
	XXX_sizecache          int32               `json:"-"`
}

func (m *MerchantDTO) Reset()         { *m = MerchantDTO{} }
func (m *MerchantDTO) String() string { return proto.CompactTextString(m) }
func (*MerchantDTO) ProtoMessage()    {}
func (*MerchantDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_merchant_1f8efe9b8d15d6b0, []int{0}
}
func (m *MerchantDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantDTO.Unmarshal(m, b)
}
func (m *MerchantDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantDTO.Marshal(b, m, deterministic)
}
func (dst *MerchantDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantDTO.Merge(dst, src)
}
func (m *MerchantDTO) XXX_Size() int {
	return xxx_messageInfo_MerchantDTO.Size(m)
}
func (m *MerchantDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantDTO.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantDTO proto.InternalMessageInfo

func (m *MerchantDTO) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MerchantDTO) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *MerchantDTO) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *MerchantDTO) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *MerchantDTO) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *MerchantDTO) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

func (m *MerchantDTO) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *MerchantDTO) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MerchantDTO) GetLimited() int64 {
	if m != nil {
		return m.Limited
	}
	return 0
}

func (m *MerchantDTO) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MerchantDTO) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *MerchantDTO) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *MerchantDTO) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *MerchantDTO) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *MerchantDTO) GetPaymentGatewaySettings() *MerchantPaygateDTO {
	if m != nil {
		return m.PaymentGatewaySettings
	}
	return nil
}

func (m *MerchantDTO) GetBusinessTypeId() string {
	if m != nil {
		return m.BusinessTypeId
	}
	return ""
}

func (m *MerchantDTO) GetBusinessLicenseStatus() string {
	if m != nil {
		return m.BusinessLicenseStatus
	}
	return ""
}

func (m *MerchantDTO) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type MerchantPaygateDTO struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	SecretKey            string   `protobuf:"bytes,3,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	WebhookUrl           string   `protobuf:"bytes,4,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantPaygateDTO) Reset()         { *m = MerchantPaygateDTO{} }
func (m *MerchantPaygateDTO) String() string { return proto.CompactTextString(m) }
func (*MerchantPaygateDTO) ProtoMessage()    {}
func (*MerchantPaygateDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_merchant_1f8efe9b8d15d6b0, []int{1}
}
func (m *MerchantPaygateDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantPaygateDTO.Unmarshal(m, b)
}
func (m *MerchantPaygateDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantPaygateDTO.Marshal(b, m, deterministic)
}
func (dst *MerchantPaygateDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantPaygateDTO.Merge(dst, src)
}
func (m *MerchantPaygateDTO) XXX_Size() int {
	return xxx_messageInfo_MerchantPaygateDTO.Size(m)
}
func (m *MerchantPaygateDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantPaygateDTO.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantPaygateDTO proto.InternalMessageInfo

func (m *MerchantPaygateDTO) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *MerchantPaygateDTO) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *MerchantPaygateDTO) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *MerchantPaygateDTO) GetWebhookUrl() string {
	if m != nil {
		return m.WebhookUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*MerchantDTO)(nil), "service_user.MerchantDTO")
	proto.RegisterType((*MerchantPaygateDTO)(nil), "service_user.MerchantPaygateDTO")
}

func init() {
	proto.RegisterFile("service_user/merchant.proto", fileDescriptor_merchant_1f8efe9b8d15d6b0)
}

var fileDescriptor_merchant_1f8efe9b8d15d6b0 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0x5d, 0x6b, 0x13, 0x41,
	0x14, 0x25, 0x69, 0x9a, 0x26, 0x37, 0x35, 0xd6, 0x41, 0xeb, 0xc5, 0x2a, 0x2e, 0x7d, 0xca, 0x53,
	0x04, 0x05, 0xdf, 0xc5, 0x88, 0x2c, 0x8d, 0x6d, 0x48, 0x52, 0x04, 0x5f, 0x96, 0xd9, 0x9d, 0x4b,
	0x32, 0x74, 0xbf, 0x98, 0x99, 0xb5, 0xec, 0x4f, 0xf0, 0x2f, 0xf9, 0xeb, 0x64, 0x3e, 0x36, 0x06,
	0xfa, 0x76, 0xcf, 0x39, 0x73, 0xef, 0x9c, 0x99, 0x7b, 0xe0, 0x4a, 0x93, 0xfa, 0x2d, 0x33, 0x4a,
	0x1a, 0x4d, 0xea, 0x43, 0x41, 0x2a, 0xdb, 0xf3, 0xd2, 0xcc, 0x6b, 0x55, 0x99, 0x8a, 0x9d, 0x1f,
	0x8b, 0xd7, 0x7f, 0x07, 0x30, 0xf9, 0x11, 0x0e, 0x2c, 0xb6, 0x77, 0x6c, 0x0a, 0xfd, 0x58, 0x60,
	0x2f, 0xea, 0xcd, 0xc6, 0xeb, 0x7e, 0x2c, 0xd8, 0x4b, 0x38, 0xfd, 0x56, 0x70, 0x99, 0x63, 0xdf,
	0x51, 0x1e, 0x30, 0x06, 0x83, 0xaf, 0x95, 0x20, 0x3c, 0x71, 0xa4, 0xab, 0x2d, 0xb7, 0xac, 0x76,
	0x15, 0x0e, 0x3c, 0x67, 0x6b, 0xf6, 0x16, 0xc6, 0x1b, 0xca, 0x14, 0x99, 0x1b, 0x6a, 0xf1, 0xd4,
	0x09, 0xff, 0x09, 0xdb, 0xb1, 0xe1, 0xb9, 0xc1, 0xa1, 0xef, 0xb0, 0x35, 0xbb, 0x84, 0xe1, 0xbd,
	0x26, 0x15, 0x2f, 0xf0, 0xcc, 0xb1, 0x01, 0x31, 0x84, 0xb3, 0x2f, 0x42, 0x28, 0xd2, 0x1a, 0x47,
	0x4e, 0xe8, 0xa0, 0x55, 0x96, 0xb2, 0x90, 0x86, 0x04, 0x8e, 0xa3, 0xde, 0xec, 0x64, 0xdd, 0x41,
	0x3b, 0xff, 0x96, 0x17, 0x84, 0xe0, 0xe7, 0xdb, 0x9a, 0x45, 0x30, 0x59, 0xed, 0xab, 0x92, 0x6e,
	0x9b, 0x22, 0x25, 0x85, 0x13, 0x27, 0x1d, 0x53, 0xec, 0x0d, 0x8c, 0x56, 0x5c, 0x51, 0x69, 0x62,
	0x81, 0xe7, 0x4e, 0x3e, 0x60, 0xeb, 0x6e, 0x63, 0xb8, 0x69, 0x34, 0x3e, 0xf3, 0xee, 0x3c, 0xb2,
	0x1e, 0x7e, 0x52, 0xaa, 0xa5, 0x21, 0x9c, 0x7a, 0x77, 0x01, 0xb2, 0x5f, 0x80, 0x35, 0x6f, 0x0b,
	0x2a, 0x4d, 0xb2, 0xe3, 0x86, 0x1e, 0x79, 0x9b, 0x68, 0x32, 0x46, 0x96, 0x3b, 0x8d, 0xcf, 0xa3,
	0xde, 0x6c, 0xf2, 0x31, 0x9a, 0x1f, 0x2f, 0x64, 0xde, 0x2d, 0x63, 0xc5, 0x5b, 0xdb, 0xb0, 0xd8,
	0xde, 0xad, 0x2f, 0xc3, 0x84, 0xef, 0x7e, 0xc0, 0x26, 0xf4, 0xb3, 0x19, 0x5c, 0xa4, 0x8d, 0x96,
	0x25, 0x69, 0x9d, 0x98, 0xb6, 0xa6, 0x44, 0x0a, 0xbc, 0x70, 0xd7, 0x4f, 0x3b, 0x7e, 0xdb, 0xd6,
	0x14, 0x0b, 0xf6, 0x19, 0x5e, 0x1f, 0x4e, 0xe6, 0x32, 0xa3, 0x52, 0x53, 0xa2, 0xfd, 0x43, 0x5e,
	0xb8, 0x86, 0x57, 0x9d, 0xbc, 0xf4, 0x6a, 0x78, 0xd7, 0x3b, 0x80, 0xba, 0x49, 0x73, 0x99, 0x25,
	0x0f, 0xd4, 0x22, 0xf3, 0x0b, 0xf4, 0xcc, 0x0d, 0xb5, 0xd7, 0x7f, 0x7a, 0xc0, 0x9e, 0xfa, 0xb5,
	0xbf, 0x14, 0x86, 0xfb, 0x1c, 0x05, 0xc4, 0xae, 0x60, 0x9c, 0xe5, 0xd2, 0x7e, 0x85, 0x14, 0x21,
	0x4f, 0x23, 0x4f, 0xc4, 0xc2, 0x5e, 0xa5, 0x5d, 0x32, 0xdc, 0x55, 0x3e, 0x58, 0x63, 0x7d, 0xc8,
	0xca, 0x7b, 0x98, 0x3c, 0x52, 0xba, 0xaf, 0xaa, 0x87, 0xa4, 0x51, 0x79, 0x08, 0x19, 0x04, 0xea,
	0x5e, 0xe5, 0xe9, 0xd0, 0xa5, 0xfb, 0xd3, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x79, 0x78, 0xd8,
	0x7e, 0xfc, 0x02, 0x00, 0x00,
}
