// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_user/user_detail.proto

package service_user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserDetailDTO struct {
	User                 *UserDTO      `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Balances             []*BalanceDTO `protobuf:"bytes,2,rep,name=Balances,proto3" json:"Balances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UserDetailDTO) Reset()         { *m = UserDetailDTO{} }
func (m *UserDetailDTO) String() string { return proto.CompactTextString(m) }
func (*UserDetailDTO) ProtoMessage()    {}
func (*UserDetailDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_detail_8797a7d83a768e86, []int{0}
}
func (m *UserDetailDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDetailDTO.Unmarshal(m, b)
}
func (m *UserDetailDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDetailDTO.Marshal(b, m, deterministic)
}
func (dst *UserDetailDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDetailDTO.Merge(dst, src)
}
func (m *UserDetailDTO) XXX_Size() int {
	return xxx_messageInfo_UserDetailDTO.Size(m)
}
func (m *UserDetailDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDetailDTO.DiscardUnknown(m)
}

var xxx_messageInfo_UserDetailDTO proto.InternalMessageInfo

func (m *UserDetailDTO) GetUser() *UserDTO {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserDetailDTO) GetBalances() []*BalanceDTO {
	if m != nil {
		return m.Balances
	}
	return nil
}

func init() {
	proto.RegisterType((*UserDetailDTO)(nil), "service_user.UserDetailDTO")
}

func init() {
	proto.RegisterFile("service_user/user_detail.proto", fileDescriptor_user_detail_8797a7d83a768e86)
}

var fileDescriptor_user_detail_8797a7d83a768e86 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x8d, 0x2f, 0x2d, 0x4e, 0x2d, 0xd2, 0x07, 0x11, 0xf1, 0x29, 0xa9, 0x25, 0x89,
	0x99, 0x39, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x3c, 0xc8, 0xf2, 0x52, 0xe2, 0x18, 0xaa,
	0x21, 0xca, 0xa4, 0xa4, 0x50, 0x24, 0x92, 0x12, 0x73, 0x12, 0xf3, 0x92, 0x53, 0x21, 0x72, 0x4a,
	0x05, 0x5c, 0xbc, 0xa1, 0xc5, 0xa9, 0x45, 0x2e, 0x60, 0x63, 0x5d, 0x42, 0xfc, 0x85, 0x34, 0xb9,
	0x58, 0x40, 0x02, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0xa2, 0x7a, 0xc8, 0x7a, 0xf5, 0xc0,
	0x4a, 0x43, 0xfc, 0x83, 0xc0, 0x4a, 0x84, 0x4c, 0xb8, 0x38, 0x9c, 0x20, 0x86, 0x15, 0x4b, 0x30,
	0x29, 0x30, 0x6b, 0x70, 0x1b, 0x49, 0xa0, 0x2a, 0x87, 0xca, 0x82, 0x74, 0xc0, 0x55, 0x26, 0xb1,
	0x81, 0x2d, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xfb, 0xd3, 0x56, 0x90, 0xdd, 0x00, 0x00,
	0x00,
}
