// Code generated by mockery v2.0.0. DO NOT EDIT.

package mocks

import (
	context "context"
	service_transaction "orders-system/proto/service_transaction"

	mock "github.com/stretchr/testify/mock"
)

// ServiceHandler is an autogenerated mock type for the ServiceHandler type
type ServiceHandler struct {
	mock.Mock
}

// AccountingChangeGpay provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) AccountingChangeGpay(_a0 context.Context, _a1 *service_transaction.AccountingChangeGpayRequest, _a2 *service_transaction.AccountingChangeGpayRequest) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.AccountingChangeGpayRequest, *service_transaction.AccountingChangeGpayRequest) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccountingPromotion provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) AccountingPromotion(_a0 context.Context, _a1 *service_transaction.AccountingPromotionRequest, _a2 *service_transaction.AccountingPromotionRequest) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.AccountingPromotionRequest, *service_transaction.AccountingPromotionRequest) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccountingPromotionDeposit provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) AccountingPromotionDeposit(_a0 context.Context, _a1 *service_transaction.AccountingPromotionDepositRequest, _a2 *service_transaction.AccountingPromotionDepositRequest) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.AccountingPromotionDepositRequest, *service_transaction.AccountingPromotionDepositRequest) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccountingPromotionWithdraw provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) AccountingPromotionWithdraw(_a0 context.Context, _a1 *service_transaction.AccountingPromotionWithdrawRequest, _a2 *service_transaction.AccountingPromotionWithdrawRequest) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.AccountingPromotionWithdrawRequest, *service_transaction.AccountingPromotionWithdrawRequest) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccountingSettlement provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) AccountingSettlement(_a0 context.Context, _a1 *service_transaction.AccountingSettlementRequest, _a2 *service_transaction.AccountingSettlementRequest) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.AccountingSettlementRequest, *service_transaction.AccountingSettlementRequest) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccountingTransaction provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) AccountingTransaction(_a0 context.Context, _a1 *service_transaction.AccountingTransactionRequest, _a2 *service_transaction.AccountingTransactionResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.AccountingTransactionRequest, *service_transaction.AccountingTransactionResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CancelRefundTransaction provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) CancelRefundTransaction(_a0 context.Context, _a1 *service_transaction.CancelRefundTransactionRequest, _a2 *service_transaction.RefundTransactionResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.CancelRefundTransactionRequest, *service_transaction.RefundTransactionResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CancelTransaction provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) CancelTransaction(_a0 context.Context, _a1 *service_transaction.ETransactionDTO, _a2 *service_transaction.ETransactionDTO) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.ETransactionDTO, *service_transaction.ETransactionDTO) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CancelTransactionId provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) CancelTransactionId(_a0 context.Context, _a1 *service_transaction.CancelTransactionIdRequest, _a2 *service_transaction.CancelTransactionIdResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.CancelTransactionIdRequest, *service_transaction.CancelTransactionIdResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChangeStatusChecking provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) ChangeStatusChecking(_a0 context.Context, _a1 *service_transaction.ChangeStatusCheckingRequest, _a2 *service_transaction.ChangeStatusCheckingRequest) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.ChangeStatusCheckingRequest, *service_transaction.ChangeStatusCheckingRequest) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChangeStatusSettlement provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) ChangeStatusSettlement(_a0 context.Context, _a1 *service_transaction.ChangeStatusSettlementRequest, _a2 *service_transaction.ChangeStatusSettlementRequest) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.ChangeStatusSettlementRequest, *service_transaction.ChangeStatusSettlementRequest) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckPendingTransactionShip provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) CheckPendingTransactionShip(_a0 context.Context, _a1 *service_transaction.CheckPendingTransactionRequest, _a2 *service_transaction.CheckPendingTransactionResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.CheckPendingTransactionRequest, *service_transaction.CheckPendingTransactionResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckTransactionLimitFee provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) CheckTransactionLimitFee(_a0 context.Context, _a1 *service_transaction.CheckTransactionLimitFeeRequest, _a2 *service_transaction.CheckTransactionLimitFeeResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.CheckTransactionLimitFeeRequest, *service_transaction.CheckTransactionLimitFeeResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckTransactionQuotaAndFee provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) CheckTransactionQuotaAndFee(_a0 context.Context, _a1 *service_transaction.CheckTransactionQuotaAndFeeReq, _a2 *service_transaction.CheckTransactionQuotaAndFeeRes) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.CheckTransactionQuotaAndFeeReq, *service_transaction.CheckTransactionQuotaAndFeeRes) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConfirmRefundTransaction provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) ConfirmRefundTransaction(_a0 context.Context, _a1 *service_transaction.ConfirmRefundTransactionRequest, _a2 *service_transaction.RefundTransactionResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.ConfirmRefundTransactionRequest, *service_transaction.RefundTransactionResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConfirmTransaction provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) ConfirmTransaction(_a0 context.Context, _a1 *service_transaction.ETransactionDTO, _a2 *service_transaction.ETransactionDTO) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.ETransactionDTO, *service_transaction.ETransactionDTO) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountCheckFeeTransactionsByTimeRange provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) CountCheckFeeTransactionsByTimeRange(_a0 context.Context, _a1 *service_transaction.CountCheckFeeTransactionsByTimeRangeReq, _a2 *service_transaction.CountCheckFeeTransactionsByTimeRangeRes) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.CountCheckFeeTransactionsByTimeRangeReq, *service_transaction.CountCheckFeeTransactionsByTimeRangeRes) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountTransactionsByTimeRange provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) CountTransactionsByTimeRange(_a0 context.Context, _a1 *service_transaction.CountTransactionsRequest, _a2 *service_transaction.CountTransactionsResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.CountTransactionsRequest, *service_transaction.CountTransactionsResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DepositGpay provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) DepositGpay(_a0 context.Context, _a1 *service_transaction.DepositGpayRequest, _a2 *service_transaction.DepositGpayRequest) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.DepositGpayRequest, *service_transaction.DepositGpayRequest) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FilterTransaction provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) FilterTransaction(_a0 context.Context, _a1 *service_transaction.FilterTransactionRequest, _a2 *service_transaction.FilterTransactionResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.FilterTransactionRequest, *service_transaction.FilterTransactionResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByTransactionId provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) FindByTransactionId(_a0 context.Context, _a1 *service_transaction.FindByTransactionIdRequest, _a2 *service_transaction.FindByTransactionIdResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.FindByTransactionIdRequest, *service_transaction.FindByTransactionIdResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindCheckFeeTransactionsByTimeRange provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) FindCheckFeeTransactionsByTimeRange(_a0 context.Context, _a1 *service_transaction.FindCheckFeeTransactionsByTimeRangeReq, _a2 *service_transaction.ListETransactionDTO) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.FindCheckFeeTransactionsByTimeRangeReq, *service_transaction.ListETransactionDTO) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindRefundFeeTransactionsByTimeRange provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) FindRefundFeeTransactionsByTimeRange(_a0 context.Context, _a1 *service_transaction.FindCheckFeeTransactionsByTimeRangeReq, _a2 *service_transaction.ListETransactionDTO) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.FindCheckFeeTransactionsByTimeRangeReq, *service_transaction.ListETransactionDTO) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindTransactionByID provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) FindTransactionByID(_a0 context.Context, _a1 *service_transaction.ETransactionDTO, _a2 *service_transaction.ETransactionDTO) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.ETransactionDTO, *service_transaction.ETransactionDTO) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindTransactionByParams provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) FindTransactionByParams(_a0 context.Context, _a1 *service_transaction.ETransactionDTO, _a2 *service_transaction.ETransactionDTO) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.ETransactionDTO, *service_transaction.ETransactionDTO) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindTransactionsByIds provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) FindTransactionsByIds(_a0 context.Context, _a1 *service_transaction.FindTransactionsByIdsReq, _a2 *service_transaction.ListETransactionDTO) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.FindTransactionsByIdsReq, *service_transaction.ListETransactionDTO) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindVoidFeeTransactionsByTimeRange provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) FindVoidFeeTransactionsByTimeRange(_a0 context.Context, _a1 *service_transaction.FindCheckFeeTransactionsByTimeRangeReq, _a2 *service_transaction.ListETransactionDTO) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.FindCheckFeeTransactionsByTimeRangeReq, *service_transaction.ListETransactionDTO) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCheckFeeSuccessTransactionStatsByTimeRange provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) GetCheckFeeSuccessTransactionStatsByTimeRange(_a0 context.Context, _a1 *service_transaction.GetCheckFeeSuccessTransactionStatsByTimeRangeReq, _a2 *service_transaction.GetCheckFeeSuccessTransactionStatsByTimeRangeRes) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.GetCheckFeeSuccessTransactionStatsByTimeRangeReq, *service_transaction.GetCheckFeeSuccessTransactionStatsByTimeRangeRes) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTransactionAmountByTimeRange provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) GetTransactionAmountByTimeRange(_a0 context.Context, _a1 *service_transaction.GetTransactionAmountRequest, _a2 *service_transaction.GetTransactionAmountResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.GetTransactionAmountRequest, *service_transaction.GetTransactionAmountResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserLimit provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) GetUserLimit(_a0 context.Context, _a1 *service_transaction.CheckTransactionQuotaAndFeeReq, _a2 *service_transaction.GetUserLimitResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.CheckTransactionQuotaAndFeeReq, *service_transaction.GetUserLimitResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InitMerchantAccount provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) InitMerchantAccount(_a0 context.Context, _a1 *service_transaction.InitMerchantAccountReq, _a2 *service_transaction.InitMerchantAccountReq) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.InitMerchantAccountReq, *service_transaction.InitMerchantAccountReq) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InitPayment provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) InitPayment(_a0 context.Context, _a1 *service_transaction.TransactionDTO, _a2 *service_transaction.InitTransactionResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.TransactionDTO, *service_transaction.InitTransactionResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InitTransaction provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) InitTransaction(_a0 context.Context, _a1 *service_transaction.ETransactionDTO, _a2 *service_transaction.ETransactionDTO) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.ETransactionDTO, *service_transaction.ETransactionDTO) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MakePayment provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) MakePayment(_a0 context.Context, _a1 *service_transaction.MakePaymentRequest, _a2 *service_transaction.MakePaymentResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.MakePaymentRequest, *service_transaction.MakePaymentResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProcessCashback provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) ProcessCashback(_a0 context.Context, _a1 *service_transaction.ProcessCashbackRequest, _a2 *service_transaction.ProcessCashbackResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.ProcessCashbackRequest, *service_transaction.ProcessCashbackResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefundTransaction provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) RefundTransaction(_a0 context.Context, _a1 *service_transaction.RefundTransactionRequest, _a2 *service_transaction.RefundTransactionResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.RefundTransactionRequest, *service_transaction.RefundTransactionResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReverseTransaction provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) ReverseTransaction(_a0 context.Context, _a1 *service_transaction.ETransactionDTO, _a2 *service_transaction.ETransactionDTO) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.ETransactionDTO, *service_transaction.ETransactionDTO) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateDecrementAmount provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) UpdateDecrementAmount(_a0 context.Context, _a1 *service_transaction.UpdateDecrementAmountRequest, _a2 *service_transaction.UpdateDecrementAmountResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.UpdateDecrementAmountRequest, *service_transaction.UpdateDecrementAmountResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateIncrementAmount provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) UpdateIncrementAmount(_a0 context.Context, _a1 *service_transaction.UpdateIncrementAmountRequest, _a2 *service_transaction.UpdateIncrementAmountResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.UpdateIncrementAmountRequest, *service_transaction.UpdateIncrementAmountResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTransaction provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) UpdateTransaction(_a0 context.Context, _a1 *service_transaction.ETransactionDTO, _a2 *service_transaction.ETransactionDTO) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.ETransactionDTO, *service_transaction.ETransactionDTO) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTransactionById provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) UpdateTransactionById(_a0 context.Context, _a1 *service_transaction.TransactionRequest, _a2 *service_transaction.UpdateTransactionResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.TransactionRequest, *service_transaction.UpdateTransactionResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTransactionsByIds provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) UpdateTransactionsByIds(_a0 context.Context, _a1 *service_transaction.UpdateTransactionsByIdsReq, _a2 *service_transaction.UpdateTransactionResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.UpdateTransactionsByIdsReq, *service_transaction.UpdateTransactionResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUserIncurred provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) UpdateUserIncurred(_a0 context.Context, _a1 *service_transaction.UpdateUserIncurredRequest, _a2 *service_transaction.UpdateUserIncurredResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.UpdateUserIncurredRequest, *service_transaction.UpdateUserIncurredResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithdrawWallet provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) WithdrawWallet(_a0 context.Context, _a1 *service_transaction.WithdrawWalletRequest, _a2 *service_transaction.WithdrawWalletRequest) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_transaction.WithdrawWalletRequest, *service_transaction.WithdrawWalletRequest) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
