// Code generated by mockery v2.0.0. DO NOT EDIT.

package mocks

import (
	context "context"
	order_system "orders-system/proto/order_system"

	mock "github.com/stretchr/testify/mock"
)

// OrdersSystemServer is an autogenerated mock type for the OrdersSystemServer type
type OrdersSystemServer struct {
	mock.Mock
}

// BankLinkInfo provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) BankLinkInfo(_a0 context.Context, _a1 *order_system.BankLinkInfoRequest) (*order_system.BankLinkInfoResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.BankLinkInfoResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.BankLinkInfoRequest) *order_system.BankLinkInfoResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.BankLinkInfoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.BankLinkInfoRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BankLinkList provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) BankLinkList(_a0 context.Context, _a1 *order_system.BankLinkListRequest) (*order_system.BankLinkListResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.BankLinkListResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.BankLinkListRequest) *order_system.BankLinkListResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.BankLinkListResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.BankLinkListRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BankRetrieveOrder provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) BankRetrieveOrder(_a0 context.Context, _a1 *order_system.BankRetrieveOrderReq) (*order_system.BankRetrieveOrderRes, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.BankRetrieveOrderRes
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.BankRetrieveOrderReq) *order_system.BankRetrieveOrderRes); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.BankRetrieveOrderRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.BankRetrieveOrderReq) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BankUnlink provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) BankUnlink(_a0 context.Context, _a1 *order_system.BankUnlinkRequest) (*order_system.BankUnlinkResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.BankUnlinkResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.BankUnlinkRequest) *order_system.BankUnlinkResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.BankUnlinkResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.BankUnlinkRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuyCard provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) BuyCard(_a0 context.Context, _a1 *order_system.OrderBuyCardRequest) (*order_system.OrderBuyCardResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.OrderBuyCardResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.OrderBuyCardRequest) *order_system.OrderBuyCardResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.OrderBuyCardResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.OrderBuyCardRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Call provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) Call(_a0 context.Context, _a1 *order_system.Request) (*order_system.Response, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.Response
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.Request) *order_system.Response); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.Request) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CancelOrder provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) CancelOrder(_a0 context.Context, _a1 *order_system.CancelOrderRequest) (*order_system.CancelOrderResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.CancelOrderResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.CancelOrderRequest) *order_system.CancelOrderResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.CancelOrderResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.CancelOrderRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CancelRefundTransaction provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) CancelRefundTransaction(_a0 context.Context, _a1 *order_system.CancelRefundTransactionReq) (*order_system.CancelRefundTransactionRes, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.CancelRefundTransactionRes
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.CancelRefundTransactionReq) *order_system.CancelRefundTransactionRes); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.CancelRefundTransactionRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.CancelRefundTransactionReq) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CashIn provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) CashIn(_a0 context.Context, _a1 *order_system.OrderCashInRequest) (*order_system.OrderCashInResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.OrderCashInResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.OrderCashInRequest) *order_system.OrderCashInResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.OrderCashInResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.OrderCashInRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CashInNapas provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) CashInNapas(_a0 context.Context, _a1 *order_system.CashInNapasRequest) (*order_system.CashInNapasResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.CashInNapasResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.CashInNapasRequest) *order_system.CashInNapasResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.CashInNapasResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.CashInNapasRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CashOTP provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) CashOTP(_a0 context.Context, _a1 *order_system.OrderCashOTPRequest) (*order_system.OrderCashOTPResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.OrderCashOTPResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.OrderCashOTPRequest) *order_system.OrderCashOTPResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.OrderCashOTPResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.OrderCashOTPRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CashOut provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) CashOut(_a0 context.Context, _a1 *order_system.CashOutRequest) (*order_system.CashOutResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.CashOutResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.CashOutRequest) *order_system.CashOutResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.CashOutResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.CashOutRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckBill provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) CheckBill(_a0 context.Context, _a1 *order_system.CheckBillRequest) (*order_system.CheckBillResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.CheckBillResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.CheckBillRequest) *order_system.CheckBillResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.CheckBillResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.CheckBillRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckByPassOTP provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) CheckByPassOTP(_a0 context.Context, _a1 *order_system.CheckByPassOTPRequest) (*order_system.CheckByPassOTPResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.CheckByPassOTPResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.CheckByPassOTPRequest) *order_system.CheckByPassOTPResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.CheckByPassOTPResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.CheckByPassOTPRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckMerchantQuotaAndFee provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) CheckMerchantQuotaAndFee(_a0 context.Context, _a1 *order_system.CheckMerchantQuotaAndFeeReq) (*order_system.CheckMerchantQuotaAndFeeRes, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.CheckMerchantQuotaAndFeeRes
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.CheckMerchantQuotaAndFeeReq) *order_system.CheckMerchantQuotaAndFeeRes); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.CheckMerchantQuotaAndFeeRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.CheckMerchantQuotaAndFeeReq) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CloseVA provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) CloseVA(_a0 context.Context, _a1 *order_system.CloseVARequest) (*order_system.CloseVAResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.CloseVAResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.CloseVARequest) *order_system.CloseVAResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.CloseVAResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.CloseVARequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfirmOrder provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) ConfirmOrder(_a0 context.Context, _a1 *order_system.ConfirmOrderRequest) (*order_system.ConfirmOrderResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.ConfirmOrderResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.ConfirmOrderRequest) *order_system.ConfirmOrderResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.ConfirmOrderResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.ConfirmOrderRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfirmRefundTransaction provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) ConfirmRefundTransaction(_a0 context.Context, _a1 *order_system.ConfirmRefundTransactionReq) (*order_system.ConfirmRefundTransactionRes, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.ConfirmRefundTransactionRes
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.ConfirmRefundTransactionReq) *order_system.ConfirmRefundTransactionRes); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.ConfirmRefundTransactionRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.ConfirmRefundTransactionReq) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateVA provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) CreateVA(_a0 context.Context, _a1 *order_system.CreateVARequest) (*order_system.CreateVAResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.CreateVAResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.CreateVARequest) *order_system.CreateVAResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.CreateVAResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.CreateVARequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DepositMerchant provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) DepositMerchant(_a0 context.Context, _a1 *order_system.DepositMerchantRequest) (*order_system.DepositMerchantResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.DepositMerchantResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.DepositMerchantRequest) *order_system.DepositMerchantResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.DepositMerchantResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.DepositMerchantRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DetailVA provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) DetailVA(_a0 context.Context, _a1 *order_system.DetailVARequest) (*order_system.DetailVAResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.DetailVAResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.DetailVARequest) *order_system.DetailVAResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.DetailVAResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.DetailVARequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FundWallet2Bank provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) FundWallet2Bank(_a0 context.Context, _a1 *order_system.FundWallet2BankRequest) (*order_system.FundWallet2BankResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.FundWallet2BankResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.FundWallet2BankRequest) *order_system.FundWallet2BankResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.FundWallet2BankResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.FundWallet2BankRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FundWallet2Wallet provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) FundWallet2Wallet(_a0 context.Context, _a1 *order_system.FundWallet2WalletRequest) (*order_system.FundWallet2WalletResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.FundWallet2WalletResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.FundWallet2WalletRequest) *order_system.FundWallet2WalletResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.FundWallet2WalletResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.FundWallet2WalletRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBanks provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) GetBanks(_a0 context.Context, _a1 *order_system.GetBanksReq) (*order_system.GetBanksRes, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.GetBanksRes
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.GetBanksReq) *order_system.GetBanksRes); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.GetBanksRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.GetBanksReq) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDetailOrder provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) GetDetailOrder(_a0 context.Context, _a1 *order_system.GetDetailOrderRequest) (*order_system.GetDetailOrderResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.GetDetailOrderResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.GetDetailOrderRequest) *order_system.GetDetailOrderResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.GetDetailOrderResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.GetDetailOrderRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDetailOrderByMerchantOrderId provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) GetDetailOrderByMerchantOrderId(_a0 context.Context, _a1 *order_system.GetDetailOrderRequest) (*order_system.GetDetailOrderResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.GetDetailOrderResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.GetDetailOrderRequest) *order_system.GetDetailOrderResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.GetDetailOrderResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.GetDetailOrderRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderByMerchant provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) GetOrderByMerchant(_a0 context.Context, _a1 *order_system.GetOrderByMerchantReq) (*order_system.GetOrderByMerchantRes, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.GetOrderByMerchantRes
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.GetOrderByMerchantReq) *order_system.GetOrderByMerchantRes); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.GetOrderByMerchantRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.GetOrderByMerchantReq) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IBFTInquiry provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) IBFTInquiry(_a0 context.Context, _a1 *order_system.IBFTInquiryRequest) (*order_system.IBFTInquiryResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.IBFTInquiryResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.IBFTInquiryRequest) *order_system.IBFTInquiryResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.IBFTInquiryResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.IBFTInquiryRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IBFTTransfer provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) IBFTTransfer(_a0 context.Context, _a1 *order_system.IBFTTransferRequest) (*order_system.IBFTTransferResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.IBFTTransferResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.IBFTTransferRequest) *order_system.IBFTTransferResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.IBFTTransferResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.IBFTTransferRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InitInternationalLinkBank provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) InitInternationalLinkBank(_a0 context.Context, _a1 *order_system.LinkRequest) (*order_system.LinkResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.LinkResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.LinkRequest) *order_system.LinkResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.LinkResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.LinkRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InitOrder provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) InitOrder(_a0 context.Context, _a1 *order_system.InitOrderRequest) (*order_system.InitOrderResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.InitOrderResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.InitOrderRequest) *order_system.InitOrderResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.InitOrderResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.InitOrderRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InitPaymentToken provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) InitPaymentToken(_a0 context.Context, _a1 *order_system.InitPaymentTokenRequest) (*order_system.InitPaymentTokenResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.InitPaymentTokenResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.InitPaymentTokenRequest) *order_system.InitPaymentTokenResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.InitPaymentTokenResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.InitPaymentTokenRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Link provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) Link(_a0 context.Context, _a1 *order_system.LinkRequest) (*order_system.LinkResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.LinkResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.LinkRequest) *order_system.LinkResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.LinkResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.LinkRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Lixi provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) Lixi(_a0 context.Context, _a1 *order_system.LixiRequest) (*order_system.LixiResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.LixiResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.LixiRequest) *order_system.LixiResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.LixiResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.LixiRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NapasInitCashIn provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) NapasInitCashIn(_a0 context.Context, _a1 *order_system.NapasInitCashInRequest) (*order_system.NapasInitCashInResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.NapasInitCashInResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.NapasInitCashInRequest) *order_system.NapasInitCashInResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.NapasInitCashInResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.NapasInitCashInRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NapasLink provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) NapasLink(_a0 context.Context, _a1 *order_system.NapasInitLinkRequest) (*order_system.NapasInitLinkResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.NapasInitLinkResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.NapasInitLinkRequest) *order_system.NapasInitLinkResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.NapasInitLinkResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.NapasInitLinkRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PGInitOrder provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) PGInitOrder(_a0 context.Context, _a1 *order_system.PGInitOrderReq) (*order_system.PGInitOrderRes, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.PGInitOrderRes
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.PGInitOrderReq) *order_system.PGInitOrderRes); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.PGInitOrderRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.PGInitOrderReq) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PGInitTrans provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) PGInitTrans(_a0 context.Context, _a1 *order_system.PGInitTransReq) (*order_system.PGInitTransRes, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.PGInitTransRes
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.PGInitTransReq) *order_system.PGInitTransRes); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.PGInitTransRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.PGInitTransReq) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PayBill provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) PayBill(_a0 context.Context, _a1 *order_system.OrderPayBillRequest) (*order_system.OrderPayBillResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.OrderPayBillResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.OrderPayBillRequest) *order_system.OrderPayBillResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.OrderPayBillResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.OrderPayBillRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PayInternationalCard provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) PayInternationalCard(_a0 context.Context, _a1 *order_system.PayInternationalCardRequest) (*order_system.PayInternationalCardResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.PayInternationalCardResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.PayInternationalCardRequest) *order_system.PayInternationalCardResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.PayInternationalCardResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.PayInternationalCardRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PaymentMerchant provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) PaymentMerchant(_a0 context.Context, _a1 *order_system.PaymentMerchantRequest) (*order_system.PaymentMerchantResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.PaymentMerchantResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.PaymentMerchantRequest) *order_system.PaymentMerchantResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.PaymentMerchantResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.PaymentMerchantRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessCreditPayment provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) ProcessCreditPayment(_a0 context.Context, _a1 *order_system.ProcessCreditPaymentRequest) (*order_system.ProcessCreditPaymentResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.ProcessCreditPaymentResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.ProcessCreditPaymentRequest) *order_system.ProcessCreditPaymentResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.ProcessCreditPaymentResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.ProcessCreditPaymentRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReOpenVA provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) ReOpenVA(_a0 context.Context, _a1 *order_system.ReOpenVARequest) (*order_system.ReOpenVAResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.ReOpenVAResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.ReOpenVARequest) *order_system.ReOpenVAResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.ReOpenVAResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.ReOpenVARequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefundTransaction provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) RefundTransaction(_a0 context.Context, _a1 *order_system.RefundTransactionReq) (*order_system.RefundTransactionRes, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.RefundTransactionRes
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.RefundTransactionReq) *order_system.RefundTransactionRes); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.RefundTransactionRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.RefundTransactionReq) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TopUp provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) TopUp(_a0 context.Context, _a1 *order_system.OrderTopUpRequest) (*order_system.OrderTopUpResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.OrderTopUpResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.OrderTopUpRequest) *order_system.OrderTopUpResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.OrderTopUpResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.OrderTopUpRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransferWallet provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) TransferWallet(_a0 context.Context, _a1 *order_system.TransferWalletRequest) (*order_system.TransferWalletResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.TransferWalletResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.TransferWalletRequest) *order_system.TransferWalletResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.TransferWalletResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.TransferWalletRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCreditPayment provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) UpdateCreditPayment(_a0 context.Context, _a1 *order_system.UpdateCreditPaymentRequest) (*order_system.UpdateCreditPaymentResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.UpdateCreditPaymentResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.UpdateCreditPaymentRequest) *order_system.UpdateCreditPaymentResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.UpdateCreditPaymentResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.UpdateCreditPaymentRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrder provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) UpdateOrder(_a0 context.Context, _a1 *order_system.UpdateOrderRequest) (*order_system.UpdateOrderResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.UpdateOrderResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.UpdateOrderRequest) *order_system.UpdateOrderResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.UpdateOrderResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.UpdateOrderRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateVA provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) UpdateVA(_a0 context.Context, _a1 *order_system.UpdateVARequest) (*order_system.UpdateVAResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.UpdateVAResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.UpdateVARequest) *order_system.UpdateVAResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.UpdateVAResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.UpdateVARequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyOTPLinkBank provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) VerifyOTPLinkBank(_a0 context.Context, _a1 *order_system.VerifyOTPLinkBankRequest) (*order_system.VerifyOTPLinkBankResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.VerifyOTPLinkBankResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.VerifyOTPLinkBankRequest) *order_system.VerifyOTPLinkBankResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.VerifyOTPLinkBankResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.VerifyOTPLinkBankRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithrawMerchant provides a mock function with given fields: _a0, _a1
func (_m *OrdersSystemServer) WithrawMerchant(_a0 context.Context, _a1 *order_system.WithrawMerchantRequest) (*order_system.WithrawMerchantResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *order_system.WithrawMerchantResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.WithrawMerchantRequest) *order_system.WithrawMerchantResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.WithrawMerchantResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.WithrawMerchantRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
