// Code generated by mockery v2.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	order_system "orders-system/proto/order_system"
)

// OrdersSystemClient is an autogenerated mock type for the OrdersSystemClient type
type OrdersSystemClient struct {
	mock.Mock
}

// BankLinkInfo provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) BankLinkInfo(ctx context.Context, in *order_system.BankLinkInfoRequest, opts ...grpc.CallOption) (*order_system.BankLinkInfoResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.BankLinkInfoResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.BankLinkInfoRequest, ...grpc.CallOption) *order_system.BankLinkInfoResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.BankLinkInfoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.BankLinkInfoRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BankLinkList provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) BankLinkList(ctx context.Context, in *order_system.BankLinkListRequest, opts ...grpc.CallOption) (*order_system.BankLinkListResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.BankLinkListResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.BankLinkListRequest, ...grpc.CallOption) *order_system.BankLinkListResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.BankLinkListResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.BankLinkListRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BankRetrieveOrder provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) BankRetrieveOrder(ctx context.Context, in *order_system.BankRetrieveOrderReq, opts ...grpc.CallOption) (*order_system.BankRetrieveOrderRes, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.BankRetrieveOrderRes
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.BankRetrieveOrderReq, ...grpc.CallOption) *order_system.BankRetrieveOrderRes); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.BankRetrieveOrderRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.BankRetrieveOrderReq, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BankUnlink provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) BankUnlink(ctx context.Context, in *order_system.BankUnlinkRequest, opts ...grpc.CallOption) (*order_system.BankUnlinkResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.BankUnlinkResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.BankUnlinkRequest, ...grpc.CallOption) *order_system.BankUnlinkResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.BankUnlinkResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.BankUnlinkRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuyCard provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) BuyCard(ctx context.Context, in *order_system.OrderBuyCardRequest, opts ...grpc.CallOption) (*order_system.OrderBuyCardResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.OrderBuyCardResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.OrderBuyCardRequest, ...grpc.CallOption) *order_system.OrderBuyCardResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.OrderBuyCardResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.OrderBuyCardRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Call provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) Call(ctx context.Context, in *order_system.Request, opts ...grpc.CallOption) (*order_system.Response, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.Response
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.Request, ...grpc.CallOption) *order_system.Response); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.Request, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CancelOrder provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) CancelOrder(ctx context.Context, in *order_system.CancelOrderRequest, opts ...grpc.CallOption) (*order_system.CancelOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.CancelOrderResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.CancelOrderRequest, ...grpc.CallOption) *order_system.CancelOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.CancelOrderResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.CancelOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CancelRefundTransaction provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) CancelRefundTransaction(ctx context.Context, in *order_system.CancelRefundTransactionReq, opts ...grpc.CallOption) (*order_system.CancelRefundTransactionRes, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.CancelRefundTransactionRes
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.CancelRefundTransactionReq, ...grpc.CallOption) *order_system.CancelRefundTransactionRes); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.CancelRefundTransactionRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.CancelRefundTransactionReq, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CashIn provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) CashIn(ctx context.Context, in *order_system.OrderCashInRequest, opts ...grpc.CallOption) (*order_system.OrderCashInResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.OrderCashInResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.OrderCashInRequest, ...grpc.CallOption) *order_system.OrderCashInResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.OrderCashInResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.OrderCashInRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CashInNapas provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) CashInNapas(ctx context.Context, in *order_system.CashInNapasRequest, opts ...grpc.CallOption) (*order_system.CashInNapasResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.CashInNapasResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.CashInNapasRequest, ...grpc.CallOption) *order_system.CashInNapasResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.CashInNapasResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.CashInNapasRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CashOTP provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) CashOTP(ctx context.Context, in *order_system.OrderCashOTPRequest, opts ...grpc.CallOption) (*order_system.OrderCashOTPResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.OrderCashOTPResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.OrderCashOTPRequest, ...grpc.CallOption) *order_system.OrderCashOTPResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.OrderCashOTPResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.OrderCashOTPRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CashOut provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) CashOut(ctx context.Context, in *order_system.CashOutRequest, opts ...grpc.CallOption) (*order_system.CashOutResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.CashOutResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.CashOutRequest, ...grpc.CallOption) *order_system.CashOutResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.CashOutResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.CashOutRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckBill provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) CheckBill(ctx context.Context, in *order_system.CheckBillRequest, opts ...grpc.CallOption) (*order_system.CheckBillResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.CheckBillResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.CheckBillRequest, ...grpc.CallOption) *order_system.CheckBillResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.CheckBillResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.CheckBillRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckByPassOTP provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) CheckByPassOTP(ctx context.Context, in *order_system.CheckByPassOTPRequest, opts ...grpc.CallOption) (*order_system.CheckByPassOTPResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.CheckByPassOTPResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.CheckByPassOTPRequest, ...grpc.CallOption) *order_system.CheckByPassOTPResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.CheckByPassOTPResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.CheckByPassOTPRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckMerchantQuotaAndFee provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) CheckMerchantQuotaAndFee(ctx context.Context, in *order_system.CheckMerchantQuotaAndFeeReq, opts ...grpc.CallOption) (*order_system.CheckMerchantQuotaAndFeeRes, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.CheckMerchantQuotaAndFeeRes
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.CheckMerchantQuotaAndFeeReq, ...grpc.CallOption) *order_system.CheckMerchantQuotaAndFeeRes); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.CheckMerchantQuotaAndFeeRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.CheckMerchantQuotaAndFeeReq, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CloseVA provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) CloseVA(ctx context.Context, in *order_system.CloseVARequest, opts ...grpc.CallOption) (*order_system.CloseVAResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.CloseVAResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.CloseVARequest, ...grpc.CallOption) *order_system.CloseVAResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.CloseVAResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.CloseVARequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfirmOrder provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) ConfirmOrder(ctx context.Context, in *order_system.ConfirmOrderRequest, opts ...grpc.CallOption) (*order_system.ConfirmOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.ConfirmOrderResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.ConfirmOrderRequest, ...grpc.CallOption) *order_system.ConfirmOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.ConfirmOrderResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.ConfirmOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfirmRefundTransaction provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) ConfirmRefundTransaction(ctx context.Context, in *order_system.ConfirmRefundTransactionReq, opts ...grpc.CallOption) (*order_system.ConfirmRefundTransactionRes, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.ConfirmRefundTransactionRes
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.ConfirmRefundTransactionReq, ...grpc.CallOption) *order_system.ConfirmRefundTransactionRes); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.ConfirmRefundTransactionRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.ConfirmRefundTransactionReq, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateVA provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) CreateVA(ctx context.Context, in *order_system.CreateVARequest, opts ...grpc.CallOption) (*order_system.CreateVAResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.CreateVAResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.CreateVARequest, ...grpc.CallOption) *order_system.CreateVAResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.CreateVAResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.CreateVARequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DepositMerchant provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) DepositMerchant(ctx context.Context, in *order_system.DepositMerchantRequest, opts ...grpc.CallOption) (*order_system.DepositMerchantResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.DepositMerchantResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.DepositMerchantRequest, ...grpc.CallOption) *order_system.DepositMerchantResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.DepositMerchantResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.DepositMerchantRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DetailVA provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) DetailVA(ctx context.Context, in *order_system.DetailVARequest, opts ...grpc.CallOption) (*order_system.DetailVAResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.DetailVAResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.DetailVARequest, ...grpc.CallOption) *order_system.DetailVAResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.DetailVAResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.DetailVARequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FundWallet2Bank provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) FundWallet2Bank(ctx context.Context, in *order_system.FundWallet2BankRequest, opts ...grpc.CallOption) (*order_system.FundWallet2BankResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.FundWallet2BankResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.FundWallet2BankRequest, ...grpc.CallOption) *order_system.FundWallet2BankResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.FundWallet2BankResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.FundWallet2BankRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FundWallet2Wallet provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) FundWallet2Wallet(ctx context.Context, in *order_system.FundWallet2WalletRequest, opts ...grpc.CallOption) (*order_system.FundWallet2WalletResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.FundWallet2WalletResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.FundWallet2WalletRequest, ...grpc.CallOption) *order_system.FundWallet2WalletResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.FundWallet2WalletResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.FundWallet2WalletRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBanks provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) GetBanks(ctx context.Context, in *order_system.GetBanksReq, opts ...grpc.CallOption) (*order_system.GetBanksRes, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.GetBanksRes
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.GetBanksReq, ...grpc.CallOption) *order_system.GetBanksRes); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.GetBanksRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.GetBanksReq, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDetailOrder provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) GetDetailOrder(ctx context.Context, in *order_system.GetDetailOrderRequest, opts ...grpc.CallOption) (*order_system.GetDetailOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.GetDetailOrderResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.GetDetailOrderRequest, ...grpc.CallOption) *order_system.GetDetailOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.GetDetailOrderResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.GetDetailOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDetailOrderByMerchantOrderId provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) GetDetailOrderByMerchantOrderId(ctx context.Context, in *order_system.GetDetailOrderRequest, opts ...grpc.CallOption) (*order_system.GetDetailOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.GetDetailOrderResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.GetDetailOrderRequest, ...grpc.CallOption) *order_system.GetDetailOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.GetDetailOrderResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.GetDetailOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderByMerchant provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) GetOrderByMerchant(ctx context.Context, in *order_system.GetOrderByMerchantReq, opts ...grpc.CallOption) (*order_system.GetOrderByMerchantRes, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.GetOrderByMerchantRes
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.GetOrderByMerchantReq, ...grpc.CallOption) *order_system.GetOrderByMerchantRes); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.GetOrderByMerchantRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.GetOrderByMerchantReq, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IBFTInquiry provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) IBFTInquiry(ctx context.Context, in *order_system.IBFTInquiryRequest, opts ...grpc.CallOption) (*order_system.IBFTInquiryResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.IBFTInquiryResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.IBFTInquiryRequest, ...grpc.CallOption) *order_system.IBFTInquiryResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.IBFTInquiryResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.IBFTInquiryRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IBFTTransfer provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) IBFTTransfer(ctx context.Context, in *order_system.IBFTTransferRequest, opts ...grpc.CallOption) (*order_system.IBFTTransferResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.IBFTTransferResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.IBFTTransferRequest, ...grpc.CallOption) *order_system.IBFTTransferResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.IBFTTransferResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.IBFTTransferRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InitInternationalLinkBank provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) InitInternationalLinkBank(ctx context.Context, in *order_system.LinkRequest, opts ...grpc.CallOption) (*order_system.LinkResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.LinkResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.LinkRequest, ...grpc.CallOption) *order_system.LinkResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.LinkResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.LinkRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InitOrder provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) InitOrder(ctx context.Context, in *order_system.InitOrderRequest, opts ...grpc.CallOption) (*order_system.InitOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.InitOrderResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.InitOrderRequest, ...grpc.CallOption) *order_system.InitOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.InitOrderResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.InitOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InitPaymentToken provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) InitPaymentToken(ctx context.Context, in *order_system.InitPaymentTokenRequest, opts ...grpc.CallOption) (*order_system.InitPaymentTokenResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.InitPaymentTokenResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.InitPaymentTokenRequest, ...grpc.CallOption) *order_system.InitPaymentTokenResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.InitPaymentTokenResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.InitPaymentTokenRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Link provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) Link(ctx context.Context, in *order_system.LinkRequest, opts ...grpc.CallOption) (*order_system.LinkResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.LinkResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.LinkRequest, ...grpc.CallOption) *order_system.LinkResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.LinkResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.LinkRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Lixi provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) Lixi(ctx context.Context, in *order_system.LixiRequest, opts ...grpc.CallOption) (*order_system.LixiResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.LixiResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.LixiRequest, ...grpc.CallOption) *order_system.LixiResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.LixiResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.LixiRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NapasInitCashIn provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) NapasInitCashIn(ctx context.Context, in *order_system.NapasInitCashInRequest, opts ...grpc.CallOption) (*order_system.NapasInitCashInResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.NapasInitCashInResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.NapasInitCashInRequest, ...grpc.CallOption) *order_system.NapasInitCashInResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.NapasInitCashInResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.NapasInitCashInRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NapasLink provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) NapasLink(ctx context.Context, in *order_system.NapasInitLinkRequest, opts ...grpc.CallOption) (*order_system.NapasInitLinkResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.NapasInitLinkResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.NapasInitLinkRequest, ...grpc.CallOption) *order_system.NapasInitLinkResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.NapasInitLinkResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.NapasInitLinkRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PGInitOrder provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) PGInitOrder(ctx context.Context, in *order_system.PGInitOrderReq, opts ...grpc.CallOption) (*order_system.PGInitOrderRes, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.PGInitOrderRes
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.PGInitOrderReq, ...grpc.CallOption) *order_system.PGInitOrderRes); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.PGInitOrderRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.PGInitOrderReq, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PGInitTrans provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) PGInitTrans(ctx context.Context, in *order_system.PGInitTransReq, opts ...grpc.CallOption) (*order_system.PGInitTransRes, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.PGInitTransRes
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.PGInitTransReq, ...grpc.CallOption) *order_system.PGInitTransRes); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.PGInitTransRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.PGInitTransReq, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PayBill provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) PayBill(ctx context.Context, in *order_system.OrderPayBillRequest, opts ...grpc.CallOption) (*order_system.OrderPayBillResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.OrderPayBillResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.OrderPayBillRequest, ...grpc.CallOption) *order_system.OrderPayBillResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.OrderPayBillResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.OrderPayBillRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PayInternationalCard provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) PayInternationalCard(ctx context.Context, in *order_system.PayInternationalCardRequest, opts ...grpc.CallOption) (*order_system.PayInternationalCardResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.PayInternationalCardResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.PayInternationalCardRequest, ...grpc.CallOption) *order_system.PayInternationalCardResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.PayInternationalCardResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.PayInternationalCardRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PaymentMerchant provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) PaymentMerchant(ctx context.Context, in *order_system.PaymentMerchantRequest, opts ...grpc.CallOption) (*order_system.PaymentMerchantResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.PaymentMerchantResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.PaymentMerchantRequest, ...grpc.CallOption) *order_system.PaymentMerchantResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.PaymentMerchantResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.PaymentMerchantRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessCreditPayment provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) ProcessCreditPayment(ctx context.Context, in *order_system.ProcessCreditPaymentRequest, opts ...grpc.CallOption) (*order_system.ProcessCreditPaymentResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.ProcessCreditPaymentResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.ProcessCreditPaymentRequest, ...grpc.CallOption) *order_system.ProcessCreditPaymentResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.ProcessCreditPaymentResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.ProcessCreditPaymentRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReOpenVA provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) ReOpenVA(ctx context.Context, in *order_system.ReOpenVARequest, opts ...grpc.CallOption) (*order_system.ReOpenVAResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.ReOpenVAResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.ReOpenVARequest, ...grpc.CallOption) *order_system.ReOpenVAResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.ReOpenVAResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.ReOpenVARequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefundTransaction provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) RefundTransaction(ctx context.Context, in *order_system.RefundTransactionReq, opts ...grpc.CallOption) (*order_system.RefundTransactionRes, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.RefundTransactionRes
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.RefundTransactionReq, ...grpc.CallOption) *order_system.RefundTransactionRes); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.RefundTransactionRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.RefundTransactionReq, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TopUp provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) TopUp(ctx context.Context, in *order_system.OrderTopUpRequest, opts ...grpc.CallOption) (*order_system.OrderTopUpResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.OrderTopUpResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.OrderTopUpRequest, ...grpc.CallOption) *order_system.OrderTopUpResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.OrderTopUpResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.OrderTopUpRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransferWallet provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) TransferWallet(ctx context.Context, in *order_system.TransferWalletRequest, opts ...grpc.CallOption) (*order_system.TransferWalletResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.TransferWalletResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.TransferWalletRequest, ...grpc.CallOption) *order_system.TransferWalletResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.TransferWalletResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.TransferWalletRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCreditPayment provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) UpdateCreditPayment(ctx context.Context, in *order_system.UpdateCreditPaymentRequest, opts ...grpc.CallOption) (*order_system.UpdateCreditPaymentResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.UpdateCreditPaymentResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.UpdateCreditPaymentRequest, ...grpc.CallOption) *order_system.UpdateCreditPaymentResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.UpdateCreditPaymentResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.UpdateCreditPaymentRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrder provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) UpdateOrder(ctx context.Context, in *order_system.UpdateOrderRequest, opts ...grpc.CallOption) (*order_system.UpdateOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.UpdateOrderResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.UpdateOrderRequest, ...grpc.CallOption) *order_system.UpdateOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.UpdateOrderResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.UpdateOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateVA provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) UpdateVA(ctx context.Context, in *order_system.UpdateVARequest, opts ...grpc.CallOption) (*order_system.UpdateVAResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.UpdateVAResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.UpdateVARequest, ...grpc.CallOption) *order_system.UpdateVAResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.UpdateVAResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.UpdateVARequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyOTPLinkBank provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) VerifyOTPLinkBank(ctx context.Context, in *order_system.VerifyOTPLinkBankRequest, opts ...grpc.CallOption) (*order_system.VerifyOTPLinkBankResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.VerifyOTPLinkBankResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.VerifyOTPLinkBankRequest, ...grpc.CallOption) *order_system.VerifyOTPLinkBankResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.VerifyOTPLinkBankResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.VerifyOTPLinkBankRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithrawMerchant provides a mock function with given fields: ctx, in, opts
func (_m *OrdersSystemClient) WithrawMerchant(ctx context.Context, in *order_system.WithrawMerchantRequest, opts ...grpc.CallOption) (*order_system.WithrawMerchantResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order_system.WithrawMerchantResponse
	if rf, ok := ret.Get(0).(func(context.Context, *order_system.WithrawMerchantRequest, ...grpc.CallOption) *order_system.WithrawMerchantResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_system.WithrawMerchantResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *order_system.WithrawMerchantRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
