// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_card/card_obj.proto

package service_card

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CardObjDTO struct {
	Provider             string   `protobuf:"bytes,1,opt,name=Provider,proto3" json:"Provider,omitempty"`
	CardNumber           string   `protobuf:"bytes,2,opt,name=CardNumber,proto3" json:"CardNumber,omitempty"`
	Serial               string   `protobuf:"bytes,3,opt,name=Serial,proto3" json:"Serial,omitempty"`
	Price                string   `protobuf:"bytes,4,opt,name=Price,proto3" json:"Price,omitempty"`
	NameCard             string   `protobuf:"bytes,5,opt,name=NameCard,proto3" json:"NameCard,omitempty"`
	PackageData          string   `protobuf:"bytes,6,opt,name=PackageData,proto3" json:"PackageData,omitempty"`
	Period               string   `protobuf:"bytes,7,opt,name=Period,proto3" json:"Period,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardObjDTO) Reset()         { *m = CardObjDTO{} }
func (m *CardObjDTO) String() string { return proto.CompactTextString(m) }
func (*CardObjDTO) ProtoMessage()    {}
func (*CardObjDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_card_obj_5f94258373cd97fe, []int{0}
}
func (m *CardObjDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardObjDTO.Unmarshal(m, b)
}
func (m *CardObjDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardObjDTO.Marshal(b, m, deterministic)
}
func (dst *CardObjDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardObjDTO.Merge(dst, src)
}
func (m *CardObjDTO) XXX_Size() int {
	return xxx_messageInfo_CardObjDTO.Size(m)
}
func (m *CardObjDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_CardObjDTO.DiscardUnknown(m)
}

var xxx_messageInfo_CardObjDTO proto.InternalMessageInfo

func (m *CardObjDTO) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *CardObjDTO) GetCardNumber() string {
	if m != nil {
		return m.CardNumber
	}
	return ""
}

func (m *CardObjDTO) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *CardObjDTO) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *CardObjDTO) GetNameCard() string {
	if m != nil {
		return m.NameCard
	}
	return ""
}

func (m *CardObjDTO) GetPackageData() string {
	if m != nil {
		return m.PackageData
	}
	return ""
}

func (m *CardObjDTO) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

func init() {
	proto.RegisterType((*CardObjDTO)(nil), "service_card.CardObjDTO")
}

func init() {
	proto.RegisterFile("service_card/card_obj.proto", fileDescriptor_card_obj_5f94258373cd97fe)
}

var fileDescriptor_card_obj_5f94258373cd97fe = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xc1, 0x8a, 0xc2, 0x30,
	0x14, 0x45, 0xe9, 0xcc, 0xb4, 0x33, 0x13, 0x5d, 0x05, 0x91, 0xa0, 0x20, 0xc5, 0x95, 0x2b, 0x5d,
	0xf8, 0x09, 0x76, 0xdd, 0x06, 0x75, 0x5f, 0x5e, 0x92, 0x87, 0xa4, 0x5a, 0x22, 0xcf, 0xda, 0xaf,
	0xf4, 0xa3, 0x24, 0x89, 0x4a, 0x37, 0x81, 0x73, 0x4f, 0xc2, 0x21, 0x6c, 0x7e, 0x43, 0xea, 0xad,
	0xc6, 0x5a, 0x03, 0x99, 0x8d, 0x3f, 0x6a, 0xa7, 0x9a, 0xf5, 0x95, 0x5c, 0xe7, 0xf8, 0x78, 0x28,
	0x97, 0x8f, 0x84, 0xb1, 0x1d, 0x90, 0xa9, 0x54, 0x53, 0x1c, 0x2b, 0x3e, 0x63, 0x7f, 0x92, 0x5c,
	0x6f, 0x0d, 0x92, 0x48, 0xf2, 0x64, 0xf5, 0xbf, 0xff, 0x30, 0x5f, 0xc4, 0x9b, 0xe5, 0xbd, 0x55,
	0x48, 0xe2, 0x2b, 0xd8, 0xc1, 0xc2, 0xa7, 0x2c, 0x3b, 0x20, 0x59, 0xb8, 0x88, 0xef, 0xe0, 0x5e,
	0xc4, 0x27, 0x2c, 0x95, 0x64, 0x35, 0x8a, 0x9f, 0x30, 0x47, 0xf0, 0xa5, 0x12, 0x5a, 0xf4, 0xef,
	0x45, 0x1a, 0x4b, 0x6f, 0xe6, 0x39, 0x1b, 0x49, 0xd0, 0x67, 0x38, 0x61, 0x01, 0x1d, 0x88, 0x2c,
	0xe8, 0xe1, 0xe4, 0x5b, 0x12, 0xc9, 0x3a, 0x23, 0x7e, 0x63, 0x2b, 0x92, 0xca, 0xc2, 0x1f, 0xb7,
	0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb2, 0xbf, 0x38, 0xab, 0x02, 0x01, 0x00, 0x00,
}
