// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_card/invoice.proto

package service_card

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InvoiceDTO struct {
	TransactionId           string              `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	TransactionDate         string              `protobuf:"bytes,2,opt,name=transaction_date,json=transactionDate,proto3" json:"transaction_date,omitempty"`
	Message                 string              `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	IsPartialPaymentAllowed bool                `protobuf:"varint,4,opt,name=isPartialPaymentAllowed,proto3" json:"isPartialPaymentAllowed,omitempty"`
	Paid                    bool                `protobuf:"varint,5,opt,name=paid,proto3" json:"paid,omitempty"`
	Amount                  int64               `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	InvoiceReference        string              `protobuf:"bytes,7,opt,name=invoiceReference,proto3" json:"invoiceReference,omitempty"`
	BillingCode             string              `protobuf:"bytes,8,opt,name=billingCode,proto3" json:"billingCode,omitempty"`
	ServiceCode             string              `protobuf:"bytes,9,opt,name=service_code,json=serviceCode,proto3" json:"service_code,omitempty"`
	InvoiceAttributes       []*InvoiceAttribute `protobuf:"bytes,11,rep,name=invoiceAttributes,proto3" json:"invoiceAttributes,omitempty"`
	ProviderName            string              `protobuf:"bytes,12,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}            `json:"-"`
	XXX_unrecognized        []byte              `json:"-"`
	XXX_sizecache           int32               `json:"-"`
}

func (m *InvoiceDTO) Reset()         { *m = InvoiceDTO{} }
func (m *InvoiceDTO) String() string { return proto.CompactTextString(m) }
func (*InvoiceDTO) ProtoMessage()    {}
func (*InvoiceDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_invoice_87e1428018c09cc5, []int{0}
}
func (m *InvoiceDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvoiceDTO.Unmarshal(m, b)
}
func (m *InvoiceDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvoiceDTO.Marshal(b, m, deterministic)
}
func (dst *InvoiceDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvoiceDTO.Merge(dst, src)
}
func (m *InvoiceDTO) XXX_Size() int {
	return xxx_messageInfo_InvoiceDTO.Size(m)
}
func (m *InvoiceDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_InvoiceDTO.DiscardUnknown(m)
}

var xxx_messageInfo_InvoiceDTO proto.InternalMessageInfo

func (m *InvoiceDTO) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

func (m *InvoiceDTO) GetTransactionDate() string {
	if m != nil {
		return m.TransactionDate
	}
	return ""
}

func (m *InvoiceDTO) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *InvoiceDTO) GetIsPartialPaymentAllowed() bool {
	if m != nil {
		return m.IsPartialPaymentAllowed
	}
	return false
}

func (m *InvoiceDTO) GetPaid() bool {
	if m != nil {
		return m.Paid
	}
	return false
}

func (m *InvoiceDTO) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *InvoiceDTO) GetInvoiceReference() string {
	if m != nil {
		return m.InvoiceReference
	}
	return ""
}

func (m *InvoiceDTO) GetBillingCode() string {
	if m != nil {
		return m.BillingCode
	}
	return ""
}

func (m *InvoiceDTO) GetServiceCode() string {
	if m != nil {
		return m.ServiceCode
	}
	return ""
}

func (m *InvoiceDTO) GetInvoiceAttributes() []*InvoiceAttribute {
	if m != nil {
		return m.InvoiceAttributes
	}
	return nil
}

func (m *InvoiceDTO) GetProviderName() string {
	if m != nil {
		return m.ProviderName
	}
	return ""
}

type InvoiceAttribute struct {
	InvoiceId              int64    `protobuf:"varint,1,opt,name=invoiceId,proto3" json:"invoiceId,omitempty"`
	InvoiceAttributeTypeId string   `protobuf:"bytes,2,opt,name=invoiceAttributeTypeId,proto3" json:"invoiceAttributeTypeId,omitempty"`
	Value                  string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Created                string   `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *InvoiceAttribute) Reset()         { *m = InvoiceAttribute{} }
func (m *InvoiceAttribute) String() string { return proto.CompactTextString(m) }
func (*InvoiceAttribute) ProtoMessage()    {}
func (*InvoiceAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_invoice_87e1428018c09cc5, []int{1}
}
func (m *InvoiceAttribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvoiceAttribute.Unmarshal(m, b)
}
func (m *InvoiceAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvoiceAttribute.Marshal(b, m, deterministic)
}
func (dst *InvoiceAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvoiceAttribute.Merge(dst, src)
}
func (m *InvoiceAttribute) XXX_Size() int {
	return xxx_messageInfo_InvoiceAttribute.Size(m)
}
func (m *InvoiceAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_InvoiceAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_InvoiceAttribute proto.InternalMessageInfo

func (m *InvoiceAttribute) GetInvoiceId() int64 {
	if m != nil {
		return m.InvoiceId
	}
	return 0
}

func (m *InvoiceAttribute) GetInvoiceAttributeTypeId() string {
	if m != nil {
		return m.InvoiceAttributeTypeId
	}
	return ""
}

func (m *InvoiceAttribute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *InvoiceAttribute) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

type VendorDTO struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string      `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Status               string      `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Type                 string      `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Fee                  int64       `protobuf:"varint,6,opt,name=fee,proto3" json:"fee,omitempty"`
	FeeType              string      `protobuf:"bytes,7,opt,name=feeType,proto3" json:"feeType,omitempty"`
	FeeMin               int64       `protobuf:"varint,8,opt,name=feeMin,proto3" json:"feeMin,omitempty"`
	FeeMax               int64       `protobuf:"varint,9,opt,name=feeMax,proto3" json:"feeMax,omitempty"`
	ImageDetail          string      `protobuf:"bytes,10,opt,name=imageDetail,proto3" json:"imageDetail,omitempty"`
	FeeBlock             []*FeeBlock `protobuf:"bytes,11,rep,name=feeBlock,proto3" json:"feeBlock,omitempty"`
	Logo                 string      `protobuf:"bytes,12,opt,name=logo,proto3" json:"logo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *VendorDTO) Reset()         { *m = VendorDTO{} }
func (m *VendorDTO) String() string { return proto.CompactTextString(m) }
func (*VendorDTO) ProtoMessage()    {}
func (*VendorDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_invoice_87e1428018c09cc5, []int{2}
}
func (m *VendorDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VendorDTO.Unmarshal(m, b)
}
func (m *VendorDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VendorDTO.Marshal(b, m, deterministic)
}
func (dst *VendorDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VendorDTO.Merge(dst, src)
}
func (m *VendorDTO) XXX_Size() int {
	return xxx_messageInfo_VendorDTO.Size(m)
}
func (m *VendorDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_VendorDTO.DiscardUnknown(m)
}

var xxx_messageInfo_VendorDTO proto.InternalMessageInfo

func (m *VendorDTO) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VendorDTO) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VendorDTO) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *VendorDTO) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *VendorDTO) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *VendorDTO) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *VendorDTO) GetFeeType() string {
	if m != nil {
		return m.FeeType
	}
	return ""
}

func (m *VendorDTO) GetFeeMin() int64 {
	if m != nil {
		return m.FeeMin
	}
	return 0
}

func (m *VendorDTO) GetFeeMax() int64 {
	if m != nil {
		return m.FeeMax
	}
	return 0
}

func (m *VendorDTO) GetImageDetail() string {
	if m != nil {
		return m.ImageDetail
	}
	return ""
}

func (m *VendorDTO) GetFeeBlock() []*FeeBlock {
	if m != nil {
		return m.FeeBlock
	}
	return nil
}

func (m *VendorDTO) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

type FeeBlock struct {
	Start                int64    `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Fee                  int64    `protobuf:"varint,3,opt,name=fee,proto3" json:"fee,omitempty"`
	Block                int64    `protobuf:"varint,4,opt,name=block,proto3" json:"block,omitempty"`
	FeeBlock             int64    `protobuf:"varint,5,opt,name=feeBlock,proto3" json:"feeBlock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeeBlock) Reset()         { *m = FeeBlock{} }
func (m *FeeBlock) String() string { return proto.CompactTextString(m) }
func (*FeeBlock) ProtoMessage()    {}
func (*FeeBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_invoice_87e1428018c09cc5, []int{3}
}
func (m *FeeBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeeBlock.Unmarshal(m, b)
}
func (m *FeeBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeeBlock.Marshal(b, m, deterministic)
}
func (dst *FeeBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeBlock.Merge(dst, src)
}
func (m *FeeBlock) XXX_Size() int {
	return xxx_messageInfo_FeeBlock.Size(m)
}
func (m *FeeBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeBlock.DiscardUnknown(m)
}

var xxx_messageInfo_FeeBlock proto.InternalMessageInfo

func (m *FeeBlock) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *FeeBlock) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *FeeBlock) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *FeeBlock) GetBlock() int64 {
	if m != nil {
		return m.Block
	}
	return 0
}

func (m *FeeBlock) GetFeeBlock() int64 {
	if m != nil {
		return m.FeeBlock
	}
	return 0
}

func init() {
	proto.RegisterType((*InvoiceDTO)(nil), "service_card.InvoiceDTO")
	proto.RegisterType((*InvoiceAttribute)(nil), "service_card.InvoiceAttribute")
	proto.RegisterType((*VendorDTO)(nil), "service_card.VendorDTO")
	proto.RegisterType((*FeeBlock)(nil), "service_card.FeeBlock")
}

func init() {
	proto.RegisterFile("service_card/invoice.proto", fileDescriptor_invoice_87e1428018c09cc5)
}

var fileDescriptor_invoice_87e1428018c09cc5 = []byte{
	// 539 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xdd, 0x8a, 0x1a, 0x4d,
	0x10, 0x45, 0x47, 0x5d, 0xa7, 0x74, 0xf7, 0xf3, 0x6b, 0x16, 0xd3, 0x2c, 0x21, 0x18, 0x43, 0xc0,
	0xe4, 0xc2, 0xc0, 0x06, 0x42, 0x6e, 0x37, 0x91, 0x80, 0x90, 0x9f, 0x65, 0x58, 0x72, 0x2b, 0xed,
	0x4c, 0x29, 0x4d, 0x66, 0xba, 0xa5, 0xa7, 0x35, 0xeb, 0x9b, 0xe4, 0x45, 0xf2, 0x02, 0x79, 0xb2,
	0xd0, 0xd5, 0x3d, 0x3a, 0x71, 0xd9, 0xbb, 0x3a, 0xa7, 0xce, 0x54, 0x57, 0xd5, 0x29, 0x06, 0xae,
	0x4a, 0x34, 0x3b, 0x99, 0xe2, 0x22, 0x15, 0x26, 0x7b, 0x23, 0xd5, 0x4e, 0xcb, 0x14, 0xa7, 0x1b,
	0xa3, 0xad, 0x66, 0xfd, 0x7a, 0x6e, 0xfc, 0x27, 0x02, 0x98, 0xfb, 0xfc, 0xec, 0xee, 0x1b, 0x7b,
	0x09, 0x17, 0xd6, 0x08, 0x55, 0x8a, 0xd4, 0x4a, 0xad, 0x16, 0x32, 0xe3, 0x8d, 0x51, 0x63, 0x12,
	0x27, 0xe7, 0x35, 0x76, 0x9e, 0xb1, 0x57, 0x30, 0xa8, 0xcb, 0x32, 0x61, 0x91, 0x37, 0x49, 0xf8,
	0x5f, 0x8d, 0x9f, 0x09, 0x8b, 0x8c, 0xc3, 0x59, 0x81, 0x65, 0x29, 0xd6, 0xc8, 0x23, 0x52, 0x54,
	0x90, 0xbd, 0x87, 0x27, 0xb2, 0xbc, 0x15, 0xc6, 0x4a, 0x91, 0xdf, 0x8a, 0x7d, 0x81, 0xca, 0xde,
	0xe4, 0xb9, 0xfe, 0x89, 0x19, 0x6f, 0x8d, 0x1a, 0x93, 0x6e, 0xf2, 0x58, 0x9a, 0x31, 0x68, 0x6d,
	0x84, 0xcc, 0x78, 0x9b, 0x64, 0x14, 0xb3, 0x21, 0x74, 0x44, 0xa1, 0xb7, 0xca, 0xf2, 0xce, 0xa8,
	0x31, 0x89, 0x92, 0x80, 0xd8, 0x6b, 0x18, 0x84, 0xf9, 0x13, 0x5c, 0xa1, 0x41, 0x95, 0x22, 0x3f,
	0xa3, 0x46, 0x1e, 0xf0, 0x6c, 0x04, 0xbd, 0xa5, 0xcc, 0x73, 0xa9, 0xd6, 0x1f, 0x75, 0x86, 0xbc,
	0x4b, 0xb2, 0x3a, 0xc5, 0x9e, 0xc3, 0x71, 0x7d, 0x4e, 0x12, 0x7b, 0x49, 0xe0, 0x48, 0xf2, 0x19,
	0xfe, 0x0f, 0x85, 0x6f, 0xac, 0x35, 0x72, 0xb9, 0xb5, 0x58, 0xf2, 0xde, 0x28, 0x9a, 0xf4, 0xae,
	0x9f, 0x4d, 0xeb, 0xbb, 0x9f, 0xce, 0x4f, 0x64, 0xc9, 0xc3, 0x0f, 0xd9, 0x0b, 0x38, 0xdf, 0x18,
	0xbd, 0x93, 0x19, 0x9a, 0x85, 0x12, 0x05, 0xf2, 0x3e, 0xbd, 0xd8, 0xaf, 0xc8, 0xaf, 0xa2, 0xc0,
	0xf1, 0xaf, 0x06, 0x0c, 0x4e, 0x8b, 0xb1, 0xa7, 0x10, 0x87, 0x72, 0x73, 0xef, 0x62, 0x94, 0x1c,
	0x09, 0xf6, 0x0e, 0x86, 0xa7, 0x8f, 0xdd, 0xed, 0x37, 0x4e, 0xea, 0x7d, 0x7c, 0x24, 0xcb, 0x2e,
	0xa1, 0xbd, 0x13, 0xf9, 0xb6, 0x32, 0xd3, 0x03, 0x67, 0x72, 0x6a, 0x50, 0xd8, 0x60, 0x5d, 0x9c,
	0x54, 0x70, 0xfc, 0xbb, 0x09, 0xf1, 0x77, 0x54, 0x99, 0x36, 0xee, 0xbc, 0x2e, 0xa0, 0x79, 0x38,
	0xa9, 0xa6, 0x24, 0x23, 0x69, 0x28, 0xff, 0x26, 0xc5, 0x8e, 0xa3, 0xd5, 0xfa, 0x07, 0x28, 0x76,
	0xe6, 0x96, 0x56, 0xd8, 0x6d, 0x19, 0xca, 0x07, 0xe4, 0xb4, 0x76, 0xbf, 0x41, 0x3a, 0x84, 0x38,
	0xa1, 0x98, 0x0d, 0x20, 0x5a, 0x21, 0x86, 0x2b, 0x70, 0xa1, 0xeb, 0x6e, 0x85, 0x34, 0x40, 0x70,
	0xbe, 0x82, 0xae, 0xee, 0x0a, 0xf1, 0x8b, 0x54, 0xe4, 0x75, 0x94, 0x04, 0x54, 0xf1, 0xe2, 0x9e,
	0x0c, 0x0e, 0xbc, 0xb8, 0x77, 0x07, 0x22, 0x0b, 0xb1, 0xc6, 0x19, 0x5a, 0x21, 0x73, 0x0e, 0xde,
	0xfd, 0x1a, 0xc5, 0xae, 0xa1, 0xbb, 0x42, 0xfc, 0x90, 0xeb, 0xf4, 0x47, 0x30, 0x7d, 0xf8, 0xaf,
	0xe9, 0x9f, 0x42, 0x36, 0x39, 0xe8, 0xdc, 0x14, 0xb9, 0x5e, 0xeb, 0x60, 0x2d, 0xc5, 0xe3, 0x1d,
	0x74, 0x2b, 0xa5, 0xdb, 0x79, 0x69, 0x85, 0xb1, 0xc1, 0x45, 0x0f, 0xdc, 0x9c, 0xa8, 0xbc, 0x5d,
	0x51, 0xe2, 0xc2, 0x6a, 0xf2, 0xe8, 0x38, 0xf9, 0x25, 0xb4, 0x97, 0xd4, 0x4a, 0xcb, 0x7f, 0x49,
	0x80, 0x5d, 0xd5, 0x7a, 0x6c, 0x53, 0xe2, 0x80, 0x97, 0x1d, 0xfa, 0x49, 0xbc, 0xfd, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0xc9, 0xeb, 0xd7, 0x73, 0x42, 0x04, 0x00, 0x00,
}
