// Code generated by mockery v2.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/micro/go-micro/v2/client"

	mock "github.com/stretchr/testify/mock"

	service_promotion "orders-system/proto/service_promotion"
)

// PromotionServicesService is an autogenerated mock type for the PromotionServicesService type
type PromotionServicesService struct {
	mock.Mock
}

// BuyVoucher provides a mock function with given fields: ctx, in, opts
func (_m *PromotionServicesService) BuyVoucher(ctx context.Context, in *service_promotion.BuyVoucherRequest, opts ...client.CallOption) (*service_promotion.BuyVoucherResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *service_promotion.BuyVoucherResponse
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.BuyVoucherRequest, ...client.CallOption) *service_promotion.BuyVoucherResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service_promotion.BuyVoucherResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service_promotion.BuyVoucherRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckLogBuyVoucherAutoBuy provides a mock function with given fields: ctx, in, opts
func (_m *PromotionServicesService) CheckLogBuyVoucherAutoBuy(ctx context.Context, in *service_promotion.CheckLogBuyVoucherAutoBuyRequest, opts ...client.CallOption) (*service_promotion.CheckLogBuyVoucherAutoBuyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *service_promotion.CheckLogBuyVoucherAutoBuyResponse
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.CheckLogBuyVoucherAutoBuyRequest, ...client.CallOption) *service_promotion.CheckLogBuyVoucherAutoBuyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service_promotion.CheckLogBuyVoucherAutoBuyResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service_promotion.CheckLogBuyVoucherAutoBuyRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckLogsUserLuckyMoney provides a mock function with given fields: ctx, in, opts
func (_m *PromotionServicesService) CheckLogsUserLuckyMoney(ctx context.Context, in *service_promotion.CheckLogsUserLuckyMoneyRequest, opts ...client.CallOption) (*service_promotion.CheckLogsUserLuckyMoneyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *service_promotion.CheckLogsUserLuckyMoneyResponse
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.CheckLogsUserLuckyMoneyRequest, ...client.CallOption) *service_promotion.CheckLogsUserLuckyMoneyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service_promotion.CheckLogsUserLuckyMoneyResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service_promotion.CheckLogsUserLuckyMoneyRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckPromotion provides a mock function with given fields: ctx, in, opts
func (_m *PromotionServicesService) CheckPromotion(ctx context.Context, in *service_promotion.CheckPromotionRequest, opts ...client.CallOption) (*service_promotion.CheckPromotionResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *service_promotion.CheckPromotionResponse
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.CheckPromotionRequest, ...client.CallOption) *service_promotion.CheckPromotionResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service_promotion.CheckPromotionResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service_promotion.CheckPromotionRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckUserLuckyMoney provides a mock function with given fields: ctx, in, opts
func (_m *PromotionServicesService) CheckUserLuckyMoney(ctx context.Context, in *service_promotion.CheckUserLuckyMoneyRequest, opts ...client.CallOption) (*service_promotion.CheckUserLuckyMoneyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *service_promotion.CheckUserLuckyMoneyResponse
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.CheckUserLuckyMoneyRequest, ...client.CallOption) *service_promotion.CheckUserLuckyMoneyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service_promotion.CheckUserLuckyMoneyResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service_promotion.CheckUserLuckyMoneyRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDetailPromotion provides a mock function with given fields: ctx, in, opts
func (_m *PromotionServicesService) GetDetailPromotion(ctx context.Context, in *service_promotion.GetDetailPromotionRequest, opts ...client.CallOption) (*service_promotion.GetDetailPromotionResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *service_promotion.GetDetailPromotionResponse
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.GetDetailPromotionRequest, ...client.CallOption) *service_promotion.GetDetailPromotionResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service_promotion.GetDetailPromotionResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service_promotion.GetDetailPromotionRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListLuckyMoneyAmount provides a mock function with given fields: ctx, in, opts
func (_m *PromotionServicesService) GetListLuckyMoneyAmount(ctx context.Context, in *service_promotion.GetListLuckyMoneyAmountRequest, opts ...client.CallOption) (*service_promotion.GetListLuckyMoneyAmountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *service_promotion.GetListLuckyMoneyAmountResponse
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.GetListLuckyMoneyAmountRequest, ...client.CallOption) *service_promotion.GetListLuckyMoneyAmountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service_promotion.GetListLuckyMoneyAmountResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service_promotion.GetListLuckyMoneyAmountRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListLuckyMoneyMessage provides a mock function with given fields: ctx, in, opts
func (_m *PromotionServicesService) GetListLuckyMoneyMessage(ctx context.Context, in *service_promotion.GetListLuckyMoneyMessageRequest, opts ...client.CallOption) (*service_promotion.GetListLuckyMoneyMessageResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *service_promotion.GetListLuckyMoneyMessageResponse
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.GetListLuckyMoneyMessageRequest, ...client.CallOption) *service_promotion.GetListLuckyMoneyMessageResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service_promotion.GetListLuckyMoneyMessageResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service_promotion.GetListLuckyMoneyMessageRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListPopup provides a mock function with given fields: ctx, in, opts
func (_m *PromotionServicesService) GetListPopup(ctx context.Context, in *service_promotion.GetListPopupRequest, opts ...client.CallOption) (*service_promotion.GetListPopupResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *service_promotion.GetListPopupResponse
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.GetListPopupRequest, ...client.CallOption) *service_promotion.GetListPopupResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service_promotion.GetListPopupResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service_promotion.GetListPopupRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListPromotion provides a mock function with given fields: ctx, in, opts
func (_m *PromotionServicesService) GetListPromotion(ctx context.Context, in *service_promotion.GetListPromotionRequest, opts ...client.CallOption) (*service_promotion.GetListPromotionResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *service_promotion.GetListPromotionResponse
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.GetListPromotionRequest, ...client.CallOption) *service_promotion.GetListPromotionResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service_promotion.GetListPromotionResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service_promotion.GetListPromotionRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLuckMoneyFindByCode provides a mock function with given fields: ctx, in, opts
func (_m *PromotionServicesService) GetLuckMoneyFindByCode(ctx context.Context, in *service_promotion.GetLuckMoneyFindByCodeRequest, opts ...client.CallOption) (*service_promotion.GetLuckMoneyFindByCodeResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *service_promotion.GetLuckMoneyFindByCodeResponse
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.GetLuckMoneyFindByCodeRequest, ...client.CallOption) *service_promotion.GetLuckMoneyFindByCodeResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service_promotion.GetLuckMoneyFindByCodeResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service_promotion.GetLuckMoneyFindByCodeRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMyPromotion provides a mock function with given fields: ctx, in, opts
func (_m *PromotionServicesService) GetMyPromotion(ctx context.Context, in *service_promotion.GetMyPromotionRequest, opts ...client.CallOption) (*service_promotion.GetMyPromotionResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *service_promotion.GetMyPromotionResponse
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.GetMyPromotionRequest, ...client.CallOption) *service_promotion.GetMyPromotionResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service_promotion.GetMyPromotionResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service_promotion.GetMyPromotionRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertLogsLuckyMoney provides a mock function with given fields: ctx, in, opts
func (_m *PromotionServicesService) InsertLogsLuckyMoney(ctx context.Context, in *service_promotion.InsertLogsLuckyMoneyRequest, opts ...client.CallOption) (*service_promotion.InsertLogsLuckyMoneyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *service_promotion.InsertLogsLuckyMoneyResponse
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.InsertLogsLuckyMoneyRequest, ...client.CallOption) *service_promotion.InsertLogsLuckyMoneyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service_promotion.InsertLogsLuckyMoneyResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service_promotion.InsertLogsLuckyMoneyRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReverseWallet provides a mock function with given fields: ctx, in, opts
func (_m *PromotionServicesService) ReverseWallet(ctx context.Context, in *service_promotion.ReverseWalletRequest, opts ...client.CallOption) (*service_promotion.ReverseWalletRequest, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *service_promotion.ReverseWalletRequest
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.ReverseWalletRequest, ...client.CallOption) *service_promotion.ReverseWalletRequest); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service_promotion.ReverseWalletRequest)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service_promotion.ReverseWalletRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateIncreScanLuckymoney provides a mock function with given fields: ctx, in, opts
func (_m *PromotionServicesService) UpdateIncreScanLuckymoney(ctx context.Context, in *service_promotion.UpdateIncreScanLuckymoneyRequest, opts ...client.CallOption) (*service_promotion.UpdateIncreScanLuckymoneyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *service_promotion.UpdateIncreScanLuckymoneyResponse
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.UpdateIncreScanLuckymoneyRequest, ...client.CallOption) *service_promotion.UpdateIncreScanLuckymoneyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service_promotion.UpdateIncreScanLuckymoneyResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service_promotion.UpdateIncreScanLuckymoneyRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UseVoucher provides a mock function with given fields: ctx, in, opts
func (_m *PromotionServicesService) UseVoucher(ctx context.Context, in *service_promotion.UseVoucherRequest, opts ...client.CallOption) (*service_promotion.UseVoucherResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *service_promotion.UseVoucherResponse
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.UseVoucherRequest, ...client.CallOption) *service_promotion.UseVoucherResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service_promotion.UseVoucherResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *service_promotion.UseVoucherRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
