// Code generated by mockery v2.0.0. DO NOT EDIT.

package mocks

import (
	context "context"
	service_promotion "orders-system/proto/service_promotion"

	mock "github.com/stretchr/testify/mock"
)

// PromotionServicesHandler is an autogenerated mock type for the PromotionServicesHandler type
type PromotionServicesHandler struct {
	mock.Mock
}

// BuyVoucher provides a mock function with given fields: _a0, _a1, _a2
func (_m *PromotionServicesHandler) BuyVoucher(_a0 context.Context, _a1 *service_promotion.BuyVoucherRequest, _a2 *service_promotion.BuyVoucherResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.BuyVoucherRequest, *service_promotion.BuyVoucherResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckLogBuyVoucherAutoBuy provides a mock function with given fields: _a0, _a1, _a2
func (_m *PromotionServicesHandler) CheckLogBuyVoucherAutoBuy(_a0 context.Context, _a1 *service_promotion.CheckLogBuyVoucherAutoBuyRequest, _a2 *service_promotion.CheckLogBuyVoucherAutoBuyResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.CheckLogBuyVoucherAutoBuyRequest, *service_promotion.CheckLogBuyVoucherAutoBuyResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckLogsUserLuckyMoney provides a mock function with given fields: _a0, _a1, _a2
func (_m *PromotionServicesHandler) CheckLogsUserLuckyMoney(_a0 context.Context, _a1 *service_promotion.CheckLogsUserLuckyMoneyRequest, _a2 *service_promotion.CheckLogsUserLuckyMoneyResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.CheckLogsUserLuckyMoneyRequest, *service_promotion.CheckLogsUserLuckyMoneyResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckPromotion provides a mock function with given fields: _a0, _a1, _a2
func (_m *PromotionServicesHandler) CheckPromotion(_a0 context.Context, _a1 *service_promotion.CheckPromotionRequest, _a2 *service_promotion.CheckPromotionResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.CheckPromotionRequest, *service_promotion.CheckPromotionResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckUserLuckyMoney provides a mock function with given fields: _a0, _a1, _a2
func (_m *PromotionServicesHandler) CheckUserLuckyMoney(_a0 context.Context, _a1 *service_promotion.CheckUserLuckyMoneyRequest, _a2 *service_promotion.CheckUserLuckyMoneyResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.CheckUserLuckyMoneyRequest, *service_promotion.CheckUserLuckyMoneyResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDetailPromotion provides a mock function with given fields: _a0, _a1, _a2
func (_m *PromotionServicesHandler) GetDetailPromotion(_a0 context.Context, _a1 *service_promotion.GetDetailPromotionRequest, _a2 *service_promotion.GetDetailPromotionResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.GetDetailPromotionRequest, *service_promotion.GetDetailPromotionResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetListLuckyMoneyAmount provides a mock function with given fields: _a0, _a1, _a2
func (_m *PromotionServicesHandler) GetListLuckyMoneyAmount(_a0 context.Context, _a1 *service_promotion.GetListLuckyMoneyAmountRequest, _a2 *service_promotion.GetListLuckyMoneyAmountResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.GetListLuckyMoneyAmountRequest, *service_promotion.GetListLuckyMoneyAmountResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetListLuckyMoneyMessage provides a mock function with given fields: _a0, _a1, _a2
func (_m *PromotionServicesHandler) GetListLuckyMoneyMessage(_a0 context.Context, _a1 *service_promotion.GetListLuckyMoneyMessageRequest, _a2 *service_promotion.GetListLuckyMoneyMessageResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.GetListLuckyMoneyMessageRequest, *service_promotion.GetListLuckyMoneyMessageResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetListPopup provides a mock function with given fields: _a0, _a1, _a2
func (_m *PromotionServicesHandler) GetListPopup(_a0 context.Context, _a1 *service_promotion.GetListPopupRequest, _a2 *service_promotion.GetListPopupResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.GetListPopupRequest, *service_promotion.GetListPopupResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetListPromotion provides a mock function with given fields: _a0, _a1, _a2
func (_m *PromotionServicesHandler) GetListPromotion(_a0 context.Context, _a1 *service_promotion.GetListPromotionRequest, _a2 *service_promotion.GetListPromotionResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.GetListPromotionRequest, *service_promotion.GetListPromotionResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLuckMoneyFindByCode provides a mock function with given fields: _a0, _a1, _a2
func (_m *PromotionServicesHandler) GetLuckMoneyFindByCode(_a0 context.Context, _a1 *service_promotion.GetLuckMoneyFindByCodeRequest, _a2 *service_promotion.GetLuckMoneyFindByCodeResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.GetLuckMoneyFindByCodeRequest, *service_promotion.GetLuckMoneyFindByCodeResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMyPromotion provides a mock function with given fields: _a0, _a1, _a2
func (_m *PromotionServicesHandler) GetMyPromotion(_a0 context.Context, _a1 *service_promotion.GetMyPromotionRequest, _a2 *service_promotion.GetMyPromotionResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.GetMyPromotionRequest, *service_promotion.GetMyPromotionResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertLogsLuckyMoney provides a mock function with given fields: _a0, _a1, _a2
func (_m *PromotionServicesHandler) InsertLogsLuckyMoney(_a0 context.Context, _a1 *service_promotion.InsertLogsLuckyMoneyRequest, _a2 *service_promotion.InsertLogsLuckyMoneyResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.InsertLogsLuckyMoneyRequest, *service_promotion.InsertLogsLuckyMoneyResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReverseWallet provides a mock function with given fields: _a0, _a1, _a2
func (_m *PromotionServicesHandler) ReverseWallet(_a0 context.Context, _a1 *service_promotion.ReverseWalletRequest, _a2 *service_promotion.ReverseWalletRequest) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.ReverseWalletRequest, *service_promotion.ReverseWalletRequest) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateIncreScanLuckymoney provides a mock function with given fields: _a0, _a1, _a2
func (_m *PromotionServicesHandler) UpdateIncreScanLuckymoney(_a0 context.Context, _a1 *service_promotion.UpdateIncreScanLuckymoneyRequest, _a2 *service_promotion.UpdateIncreScanLuckymoneyResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.UpdateIncreScanLuckymoneyRequest, *service_promotion.UpdateIncreScanLuckymoneyResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UseVoucher provides a mock function with given fields: _a0, _a1, _a2
func (_m *PromotionServicesHandler) UseVoucher(_a0 context.Context, _a1 *service_promotion.UseVoucherRequest, _a2 *service_promotion.UseVoucherResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_promotion.UseVoucherRequest, *service_promotion.UseVoucherResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
