// Code generated by mockery v2.0.0. DO NOT EDIT.

package mocks

import (
	context "context"
	service_merchant_fee "orders-system/proto/service_merchant_fee"

	mock "github.com/stretchr/testify/mock"
)

// ServiceHandler is an autogenerated mock type for the ServiceHandler type
type ServiceHandler struct {
	mock.Mock
}

// CheckMerchantQuota provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) CheckMerchantQuota(_a0 context.Context, _a1 *service_merchant_fee.CheckMerchantQuotaRequest, _a2 *service_merchant_fee.CheckMerchantQuotaResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_merchant_fee.CheckMerchantQuotaRequest, *service_merchant_fee.CheckMerchantQuotaResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckMerchantQuotaAndFee provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) CheckMerchantQuotaAndFee(_a0 context.Context, _a1 *service_merchant_fee.CheckMerchantQuotaAndFeeReq, _a2 *service_merchant_fee.CheckMerchantQuotaAndFeeRes) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_merchant_fee.CheckMerchantQuotaAndFeeReq, *service_merchant_fee.CheckMerchantQuotaAndFeeRes) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateFeeCheckLog provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) CreateFeeCheckLog(_a0 context.Context, _a1 *service_merchant_fee.CreateFeeCheckLogReq, _a2 *service_merchant_fee.CreateFeeCheckLogRes) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_merchant_fee.CreateFeeCheckLogReq, *service_merchant_fee.CreateFeeCheckLogRes) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateFeeCheckLogPeriod provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) CreateFeeCheckLogPeriod(_a0 context.Context, _a1 *service_merchant_fee.CreateFeeCheckLogPeriodReq, _a2 *service_merchant_fee.CreateFeeCheckLogRes) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_merchant_fee.CreateFeeCheckLogPeriodReq, *service_merchant_fee.CreateFeeCheckLogRes) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CrossCheckStatusUpdates provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) CrossCheckStatusUpdates(_a0 context.Context, _a1 *service_merchant_fee.CrossCheckStatusUpdatesReq, _a2 *service_merchant_fee.CrossCheckStatusUpdatesRes) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_merchant_fee.CrossCheckStatusUpdatesReq, *service_merchant_fee.CrossCheckStatusUpdatesRes) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMerchantVendorDiscount provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) GetMerchantVendorDiscount(_a0 context.Context, _a1 *service_merchant_fee.GetMerchantVendorDiscountReq, _a2 *service_merchant_fee.GetMerchantVendorDiscountRes) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_merchant_fee.GetMerchantVendorDiscountReq, *service_merchant_fee.GetMerchantVendorDiscountRes) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LogVAManagementFee provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) LogVAManagementFee(_a0 context.Context, _a1 *service_merchant_fee.LogVAManagementFeeReq, _a2 *service_merchant_fee.LogVAManagementFeeRes) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_merchant_fee.LogVAManagementFeeReq, *service_merchant_fee.LogVAManagementFeeRes) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LogVAManagementFeePayment provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) LogVAManagementFeePayment(_a0 context.Context, _a1 *service_merchant_fee.LogVAManagementFeePaymentReq, _a2 *service_merchant_fee.LogVAManagementFeeRes) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_merchant_fee.LogVAManagementFeePaymentReq, *service_merchant_fee.LogVAManagementFeeRes) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LogVAManagementFeeUpdateCrossCheckStatus provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) LogVAManagementFeeUpdateCrossCheckStatus(_a0 context.Context, _a1 *service_merchant_fee.LogVAManagementFeeUpdateCrossCheckStatusReq, _a2 *service_merchant_fee.LogVAManagementFeeRes) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_merchant_fee.LogVAManagementFeeUpdateCrossCheckStatusReq, *service_merchant_fee.LogVAManagementFeeRes) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Settlement provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) Settlement(_a0 context.Context, _a1 *service_merchant_fee.SettlementReq, _a2 *service_merchant_fee.SettlementRes) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_merchant_fee.SettlementReq, *service_merchant_fee.SettlementRes) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
