// Code generated by mockery v2.0.0. DO NOT EDIT.

package mocks

import (
	mqtt "github.com/eclipse/paho.mqtt.golang"
	mock "github.com/stretchr/testify/mock"
)

// IMqtt is an autogenerated mock type for the IMqtt type
type IMqtt struct {
	mock.Mock
}

// Publish provides a mock function with given fields: topic, message, retain, prefix
func (_m *IMqtt) Publish(topic string, message string, retain bool, prefix string) error {
	ret := _m.Called(topic, message, retain, prefix)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, bool, string) error); ok {
		r0 = rf(topic, message, retain, prefix)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Subscribe provides a mock function with given fields: topic, c
func (_m *IMqtt) Subscribe(topic string, c func(mqtt.Client, mqtt.Message)) {
	_m.Called(topic, c)
}
