// Code generated by mockery v2.0.0. DO NOT EDIT.

package mocks

import (
	entities "orders-system/domain/entities"

	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// IVA is an autogenerated mock type for the IVA type
type IVA struct {
	mock.Mock
}

// CreateVA provides a mock function with given fields: request
func (_m *IVA) CreateVA(request entities.VirtualAccounts) (entities.VirtualAccounts, error) {
	ret := _m.Called(request)

	var r0 entities.VirtualAccounts
	if rf, ok := ret.Get(0).(func(entities.VirtualAccounts) entities.VirtualAccounts); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Get(0).(entities.VirtualAccounts)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entities.VirtualAccounts) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteVAAccount provides a mock function with given fields: accountNumber
func (_m *IVA) DeleteVAAccount(accountNumber string) error {
	ret := _m.Called(accountNumber)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(accountNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetVAByAccountNumber provides a mock function with given fields: accountNumber
func (_m *IVA) GetVAByAccountNumber(accountNumber string) (entities.VirtualAccounts, error) {
	ret := _m.Called(accountNumber)

	var r0 entities.VirtualAccounts
	if rf, ok := ret.Get(0).(func(string) entities.VirtualAccounts); ok {
		r0 = rf(accountNumber)
	} else {
		r0 = ret.Get(0).(entities.VirtualAccounts)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(accountNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVAByMapCondition provides a mock function with given fields: mapId, mapType, merchantId
func (_m *IVA) GetVAByMapCondition(mapId string, mapType string, merchantId string) (entities.VirtualAccounts, error) {
	ret := _m.Called(mapId, mapType, merchantId)

	var r0 entities.VirtualAccounts
	if rf, ok := ret.Get(0).(func(string, string, string) entities.VirtualAccounts); ok {
		r0 = rf(mapId, mapType, merchantId)
	} else {
		r0 = ret.Get(0).(entities.VirtualAccounts)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(mapId, mapType, merchantId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVAByMerchantId provides a mock function with given fields: merchantId
func (_m *IVA) GetVAByMerchantId(merchantId string) (entities.VirtualAccounts, error) {
	ret := _m.Called(merchantId)

	var r0 entities.VirtualAccounts
	if rf, ok := ret.Get(0).(func(string) entities.VirtualAccounts); ok {
		r0 = rf(merchantId)
	} else {
		r0 = ret.Get(0).(entities.VirtualAccounts)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(merchantId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementBalanceVA provides a mock function with given fields: accountNumber, balance
func (_m *IVA) IncrementBalanceVA(accountNumber string, balance int64) (entities.VirtualAccounts, error) {
	ret := _m.Called(accountNumber, balance)

	var r0 entities.VirtualAccounts
	if rf, ok := ret.Get(0).(func(string, int64) entities.VirtualAccounts); ok {
		r0 = rf(accountNumber, balance)
	} else {
		r0 = ret.Get(0).(entities.VirtualAccounts)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int64) error); ok {
		r1 = rf(accountNumber, balance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateVA provides a mock function with given fields: accountNumber, fieldUpdate
func (_m *IVA) UpdateVA(accountNumber string, fieldUpdate primitive.M) (entities.VirtualAccounts, error) {
	ret := _m.Called(accountNumber, fieldUpdate)

	var r0 entities.VirtualAccounts
	if rf, ok := ret.Get(0).(func(string, primitive.M) entities.VirtualAccounts); ok {
		r0 = rf(accountNumber, fieldUpdate)
	} else {
		r0 = ret.Get(0).(entities.VirtualAccounts)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, primitive.M) error); ok {
		r1 = rf(accountNumber, fieldUpdate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
