// Code generated by mockery v2.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	request_params "orders-system/domain/request_params"

	value_objects "orders-system/domain/value_objects"
)

// IWalletConfig is an autogenerated mock type for the IWalletConfig type
type IWalletConfig struct {
	mock.Mock
}

// GetMerchantConfig provides a mock function with given fields: ctx, req
func (_m *IWalletConfig) GetMerchantConfig(ctx context.Context, req request_params.GetMerchantConfigReq) (value_objects.GetMerchantConfigRes, error) {
	ret := _m.Called(ctx, req)

	var r0 value_objects.GetMerchantConfigRes
	if rf, ok := ret.Get(0).(func(context.Context, request_params.GetMerchantConfigReq) value_objects.GetMerchantConfigRes); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(value_objects.GetMerchantConfigRes)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, request_params.GetMerchantConfigReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRefundConfig provides a mock function with given fields: ctx, req
func (_m *IWalletConfig) GetRefundConfig(ctx context.Context, req request_params.GetRefundConfigReq) (value_objects.GetRefundConfigRes, error) {
	ret := _m.Called(ctx, req)

	var r0 value_objects.GetRefundConfigRes
	if rf, ok := ret.Get(0).(func(context.Context, request_params.GetRefundConfigReq) value_objects.GetRefundConfigRes); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(value_objects.GetRefundConfigRes)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, request_params.GetRefundConfigReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
