// Code generated by mockery v2.0.0. DO NOT EDIT.

package mocks

import (
	context "context"
	service_user "orders-system/proto/service_user"

	mock "github.com/stretchr/testify/mock"
)

// ServiceHandler is an autogenerated mock type for the ServiceHandler type
type ServiceHandler struct {
	mock.Mock
}

// CountMessageStatusUnread provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) CountMessageStatusUnread(_a0 context.Context, _a1 *service_user.NotificationRequestCountUnread, _a2 *service_user.CountMessageStatusUnreadResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.NotificationRequestCountUnread, *service_user.CountMessageStatusUnreadResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountUser provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) CountUser(_a0 context.Context, _a1 *service_user.CountUserByMonthRequest, _a2 *service_user.CountUserByMonthResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.CountUserByMonthRequest, *service_user.CountUserByMonthResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountUserDetail provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) CountUserDetail(_a0 context.Context, _a1 *service_user.CountUserDetailRequest, _a2 *service_user.CountDetail) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.CountUserDetailRequest, *service_user.CountDetail) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateDevice provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) CreateDevice(_a0 context.Context, _a1 *service_user.CreateDeviceRequest, _a2 *service_user.CreateDeviceResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.CreateDeviceRequest, *service_user.CreateDeviceResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMessageNormal provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) CreateMessageNormal(_a0 context.Context, _a1 *service_user.CreateMessageNormalRequest, _a2 *service_user.CreateMessageResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.CreateMessageNormalRequest, *service_user.CreateMessageResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTransactionMessage provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) CreateTransactionMessage(_a0 context.Context, _a1 *service_user.CreateTransactionMessageRequest, _a2 *service_user.CreateMessageResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.CreateTransactionMessageRequest, *service_user.CreateMessageResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUser provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) CreateUser(_a0 context.Context, _a1 *service_user.CreateUserRequest, _a2 *service_user.CreateUserResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.CreateUserRequest, *service_user.CreateUserResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteDevice provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) DeleteDevice(_a0 context.Context, _a1 *service_user.DeleteDeviceRequest, _a2 *service_user.DeleteDeviceResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.DeleteDeviceRequest, *service_user.DeleteDeviceResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindGGroupUserById provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) FindGGroupUserById(_a0 context.Context, _a1 *service_user.FindGGroupUserByIdRequest, _a2 *service_user.FindGGroupUserByIdResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.FindGGroupUserByIdRequest, *service_user.FindGGroupUserByIdResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindMerchantAccountByCode provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) FindMerchantAccountByCode(_a0 context.Context, _a1 *service_user.FindMerchantAccountByCodeRequest, _a2 *service_user.FindMerchantAccountByCodeResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.FindMerchantAccountByCodeRequest, *service_user.FindMerchantAccountByCodeResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindMerchantAccountByID provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) FindMerchantAccountByID(_a0 context.Context, _a1 *service_user.FindMerchantAccountByIdRequest, _a2 *service_user.FindMerchantAccountByIdResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.FindMerchantAccountByIdRequest, *service_user.FindMerchantAccountByIdResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindMerchantAccountByIDs provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) FindMerchantAccountByIDs(_a0 context.Context, _a1 *service_user.FindMerchantAccountByIDsRequest, _a2 *service_user.FindMerchantAccountByIDsResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.FindMerchantAccountByIDsRequest, *service_user.FindMerchantAccountByIDsResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindMerchantAccountByUserID provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) FindMerchantAccountByUserID(_a0 context.Context, _a1 *service_user.FindMerchantAccountByUserIdRequest, _a2 *service_user.FindMerchantAccountByUserIdResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.FindMerchantAccountByUserIdRequest, *service_user.FindMerchantAccountByUserIdResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindMerchantAccounts provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) FindMerchantAccounts(_a0 context.Context, _a1 *service_user.FindMerchantAccountsRequest, _a2 *service_user.FindMerchantAccountsResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.FindMerchantAccountsRequest, *service_user.FindMerchantAccountsResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindMerchantByTerminalId provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) FindMerchantByTerminalId(_a0 context.Context, _a1 *service_user.FindMerchantByTerminalIdReq, _a2 *service_user.FindMerchantByTerminalIdRes) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.FindMerchantByTerminalIdReq, *service_user.FindMerchantByTerminalIdRes) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindUserByEmail provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) FindUserByEmail(_a0 context.Context, _a1 *service_user.FindUserByEmailRequest, _a2 *service_user.FindUserByEmailResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.FindUserByEmailRequest, *service_user.FindUserByEmailResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindUserById provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) FindUserById(_a0 context.Context, _a1 *service_user.FindUserByIdRequest, _a2 *service_user.FindUserByIdResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.FindUserByIdRequest, *service_user.FindUserByIdResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindUserByPhone provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) FindUserByPhone(_a0 context.Context, _a1 *service_user.FindUserByPhoneRequest, _a2 *service_user.FindUserByPhoneResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.FindUserByPhoneRequest, *service_user.FindUserByPhoneResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindUserByTimeRange provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) FindUserByTimeRange(_a0 context.Context, _a1 *service_user.FindUserByTimeRangeReq, _a2 *service_user.FindUserByTimeRangeRes) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.FindUserByTimeRangeReq, *service_user.FindUserByTimeRangeRes) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindUserDetailByEmail provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) FindUserDetailByEmail(_a0 context.Context, _a1 *service_user.FindUserDetailByEmailRequest, _a2 *service_user.FindUserDetailByEmailResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.FindUserDetailByEmailRequest, *service_user.FindUserDetailByEmailResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindUserDetailById provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) FindUserDetailById(_a0 context.Context, _a1 *service_user.FindUserDetailByIdRequest, _a2 *service_user.FindUserDetailByIdResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.FindUserDetailByIdRequest, *service_user.FindUserDetailByIdResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindUserDetailByPhone provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) FindUserDetailByPhone(_a0 context.Context, _a1 *service_user.FindUserDetailByPhoneRequest, _a2 *service_user.FindUserDetailByPhoneResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.FindUserDetailByPhoneRequest, *service_user.FindUserDetailByPhoneResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindUsersByPhonePattern provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) FindUsersByPhonePattern(_a0 context.Context, _a1 *service_user.FindUsersByPhonePatternReq, _a2 *service_user.FindUsersByPhonePatternRes) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.FindUsersByPhonePatternReq, *service_user.FindUsersByPhonePatternRes) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMerchantAccount provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) GetMerchantAccount(_a0 context.Context, _a1 *service_user.GetMerchantAccountReq, _a2 *service_user.MerchantAccount) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.GetMerchantAccountReq, *service_user.MerchantAccount) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSubAccount provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) GetSubAccount(_a0 context.Context, _a1 *service_user.GetSubAccountReq, _a2 *service_user.GetSubAccountRes) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.GetSubAccountReq, *service_user.GetSubAccountRes) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTopUser provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) GetTopUser(_a0 context.Context, _a1 *service_user.GetTopUserRequest, _a2 *service_user.GetTopUserResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.GetTopUserRequest, *service_user.GetTopUserResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserAccount provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) GetUserAccount(_a0 context.Context, _a1 *service_user.GetUserAccountReq, _a2 *service_user.GetUserAccountRes) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.GetUserAccountReq, *service_user.GetUserAccountRes) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListMessage provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) ListMessage(_a0 context.Context, _a1 *service_user.NotificationRequestGetList, _a2 *service_user.ListMessageResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.NotificationRequestGetList, *service_user.ListMessageResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendSms provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) SendSms(_a0 context.Context, _a1 *service_user.SendSmsRequest, _a2 *service_user.SendSmsResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.SendSmsRequest, *service_user.SendSmsResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateDevice provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) UpdateDevice(_a0 context.Context, _a1 *service_user.UpdateDeviceRequest, _a2 *service_user.UpdateDeviceResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.UpdateDeviceRequest, *service_user.UpdateDeviceResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUser provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) UpdateUser(_a0 context.Context, _a1 *service_user.UpdateUserRequest, _a2 *service_user.UpdateUserResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.UpdateUserRequest, *service_user.UpdateUserResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUserById provides a mock function with given fields: _a0, _a1, _a2
func (_m *ServiceHandler) UpdateUserById(_a0 context.Context, _a1 *service_user.UserUpdateRequest, _a2 *service_user.UserUpdateResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service_user.UserUpdateRequest, *service_user.UserUpdateResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
