package constants

const VI = "VI"
const VND = "VNĐ"
const GPAY_ACCOUNT_ID = "GPAY0001"
const (
	TRANSACTION_STATUS_PENDING    = "PENDING"
	TRANSACTION_STATUS_PROCESSING = "PROCESSING"
	TRANSACTION_STATUS_FINISH     = "FINISH"
	TRANSACTION_STATUS_FAILED     = "FAILED"

	TRANSACTION_STATE_INITIAL = "INITIAL"
	TRANSACTION_STATE_APPLIED = "APPLIED"

	SOURCE_OF_FUND_BALANCE_WALLET = "BALANCE_WAL"
	SOURCE_OF_FUND_BANK_ATM       = "BANK_ATM"
	SOURCE_OF_FUND_CREDIT_CARD    = "CREDIT_CARD"
	SOURCE_OF_FUND_DEBIT_CARD     = "DEBIT_CARD"

	SOURCE_OF_FUND_INTERNATIONAL_CARD = "INTERNATIONAL_CARD"

	SERVICE_TYPE_COLLECTION_AND_PAY = "PAY_COLLECT"
	SERVICE_TYPE_WALLET             = "WALLET"
	SERVICE_TYPE_PAYMENT_GATEAWAY   = "PAYMENTGATEWAY"

	TRANSTYPE_BEHALF_PAY_WALLET_TO_WALLET = "WAL2WAL"
	TRANSTYPE_BEHALF_PAY_WALLET_TO_BANK   = "WAL2BANK"

	TRANSTYPE_WALLET_TRANSFER     = "TRANSFER"   //Chuyển tiền
	TRANSTYPE_WALLET_PAY          = "PAY_WAL"    // Dịch vụ/ Hóa đơn
	TRANSTYPE_WALLET_PAY_MC       = "PAY_WAL_MC" // Dịch vụ/ Hóa đơn
	TRANSTYPE_WALLET_PAY_BY_TOKEN = "PAYBYTOKEN" // Thanh toán với nguồn bằng token
	TRANSTYPE_WALLET_CASH_IN      = "CASHIN"     // Nạp tiền vào ví
	TRANSTYPE_WALLET_CASH_OUT     = "CASHOUT"    // Rút tiền khỏi ví
	TRANSTYPE_WALLET_TRANS2BANK   = "TRANS2BANK" // Rút tiền khỏi ví
	TRANSTYPE_WALLET_LIXI         = "LIXI"       //  Lì xi
	TRANSTYPE_WALLET_REFUND       = "REFUND"     //  GD hoàn tiền
	TRANSTYPE_WALLET_CASHBACK     = "CASHBACK"   //  GD CASHBACK xu
	TRANSTYPE_WALLET_CASH_IN_MC   = "CASHINMC"   // Nạp tiền vào ví
	TRANSTYPE_WALLET_CASH_OUT_MC  = "CASHOUTMC"  // Rút tiền khỏi ví

	TRANSTYPE_PAY_TO_MERCHANT = "PAY2MERCHANT"
	TRANSTYPE_PAY_VA          = "VA"

	TRANSTYPE_OPENWAL_CASHIN          = "OPENWALLET_CASHIN"
	TRANSTYPE_OPENWAL_CASHOUT         = "OPENWALLET_CASHOUT"
	TRANSTYPE_OPENWAL_PAY             = "OPENWALLET_PAY"
	TRANSTYPE_OPENWAL_WITHDRAW        = "OPENWALLET_WITHDRAW"
	TRANSTYPE_OPENWAL_TRANSFERTOBANK  = "OPENWALLET_TRANSFERTOBANK"
	TRANSTYPE_OPENWAL_TRANSFER2WALLET = "OPENWALLET_TRANSFER2WALLET"

	TRANSTYPE_PG_PAY                           = "PAY"
	TRANSTYPE_PG_PAY_BY_TOKEN                  = "PAYBYTOKEN"
	TRANSTYPE_PG_REFUND                        = "REFUND"
	TRANSTYPE_PG_PAY_BY_CREDIT                 = "PAY_CREDIT"             // pay by international card
	TRANSTYPE_PG_PAY_BY_PAY_INTERNATIONAL_CARD = "PAY_INTERNATIONAL_CARD" // pay by international card

	SUB_TRANSTYPE_WALLET_TOPUP_CARD         = "TOPUPCARD"
	SUB_TRANSTYPE_WALLET_BUY_CARD           = "BUYCARD"
	SUB_TRANSTYPE_WALLET_BUY_DATA           = "BUYDATA"
	SUB_TRANSTYPE_WALLET_PAY_BILL_WATTER    = "PAYBILLWATER"
	SUB_TRANSTYPE_WALLET_PAY_BILL_ELECTRIC  = "PAYBILLELECTRIC"
	SUB_TRANSTYPE_WALLET_PAY_BILL_LOAN      = "PAYBILLLOAN"
	SUB_TRANSTYPE_WALLET_PAY_BILL_TV        = "PAYBILLTV"        // truyen hinh
	SUB_TRANSTYPE_WALLET_PAY_BILL_INTERNET  = "PAYBILLINTERNET"  // internet
	SUB_TRANSTYPE_WALLET_PAY_BILL_TELEPHONE = "PAYBILLTELEPHONE" // dien thoai co dinh
	SUB_TRANSTYPE_WALLET_QR_STATIC          = "QRCODEMPMSTATIC"  //  static QR
	SUB_TRANSTYPE_WALLET_QR_DYNAMIC         = "QRCODEMPMDYNAMIC" //  dynamic QR
	SUB_TRANSTYPE_WALLET_WEB_TO_APP         = "WEBTOAPP"         //  WEBTOAPP
	SUB_TRANSTYPE_WALLET_WEB_IN_APP         = "WEBINAPP"         //  WEB IN APP
	SUB_TRANSTYPE_WALLET_APP_TO_APP         = "APPTOAPP"         //  APP TO APP

	SUB_TRANSTYPE_PG_PAY_DEBIT  = "PAY_DEBIT"  //  PAY_DEBIT
	SUB_TRANSTYPE_PG_PAY_CREDIT = "PAY_CREDIT" //  PAY_CREDIT

)

const (
	Amount               = "amount"
	AmountCash           = "amount_cash"
	AmountMinimum        = "amount_minimum"
	AmountRevenue        = "amount_revenue"
	AmountRefund         = "amount_refund"
	AmountCost           = "amount_cost"
	AmountWallet         = "amount_wallet"
	AmountCollectionPay  = "amount_collection_pay" // tk chuyen chi
	AmountFee            = "amount_fee"
	AmountPaymentGateway = "amount_payment_gateway" // tkdb cổng
)

const (
	MPGS_DEBIT_CARD  = "DEBIT"
	MPGS_CREDIT_CARD = "CREDIT"
)
