// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order_system/bank.proto

package order_system

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BankLinkListRequest struct {
	GpayUserID           string   `protobuf:"bytes,1,opt,name=gpayUserID,proto3" json:"gpayUserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BankLinkListRequest) Reset()         { *m = BankLinkListRequest{} }
func (m *BankLinkListRequest) String() string { return proto.CompactTextString(m) }
func (*BankLinkListRequest) ProtoMessage()    {}
func (*BankLinkListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bank_c5b0f883540c41cb, []int{0}
}
func (m *BankLinkListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankLinkListRequest.Unmarshal(m, b)
}
func (m *BankLinkListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankLinkListRequest.Marshal(b, m, deterministic)
}
func (dst *BankLinkListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankLinkListRequest.Merge(dst, src)
}
func (m *BankLinkListRequest) XXX_Size() int {
	return xxx_messageInfo_BankLinkListRequest.Size(m)
}
func (m *BankLinkListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BankLinkListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BankLinkListRequest proto.InternalMessageInfo

func (m *BankLinkListRequest) GetGpayUserID() string {
	if m != nil {
		return m.GpayUserID
	}
	return ""
}

type BankLinkListResponse struct {
	LinkDetail           []*BankLinkDetail `protobuf:"bytes,1,rep,name=LinkDetail,proto3" json:"LinkDetail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BankLinkListResponse) Reset()         { *m = BankLinkListResponse{} }
func (m *BankLinkListResponse) String() string { return proto.CompactTextString(m) }
func (*BankLinkListResponse) ProtoMessage()    {}
func (*BankLinkListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bank_c5b0f883540c41cb, []int{1}
}
func (m *BankLinkListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankLinkListResponse.Unmarshal(m, b)
}
func (m *BankLinkListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankLinkListResponse.Marshal(b, m, deterministic)
}
func (dst *BankLinkListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankLinkListResponse.Merge(dst, src)
}
func (m *BankLinkListResponse) XXX_Size() int {
	return xxx_messageInfo_BankLinkListResponse.Size(m)
}
func (m *BankLinkListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BankLinkListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BankLinkListResponse proto.InternalMessageInfo

func (m *BankLinkListResponse) GetLinkDetail() []*BankLinkDetail {
	if m != nil {
		return m.LinkDetail
	}
	return nil
}

type BankLinkDetail struct {
	LinkId               int64    `protobuf:"varint,1,opt,name=linkId,proto3" json:"linkId,omitempty"`
	CardNumber           string   `protobuf:"bytes,2,opt,name=cardNumber,proto3" json:"cardNumber,omitempty"`
	AccountNumber        string   `protobuf:"bytes,3,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	FullName             string   `protobuf:"bytes,4,opt,name=fullName,proto3" json:"fullName,omitempty"`
	GpayUserID           string   `protobuf:"bytes,5,opt,name=gpayUserID,proto3" json:"gpayUserID,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,6,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Provider             string   `protobuf:"bytes,7,opt,name=provider,proto3" json:"provider,omitempty"`
	BankCode             string   `protobuf:"bytes,8,opt,name=bankCode,proto3" json:"bankCode,omitempty"`
	GPayBankCode         string   `protobuf:"bytes,9,opt,name=gPayBankCode,proto3" json:"gPayBankCode,omitempty"`
	Status               string   `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	BankLogo             string   `protobuf:"bytes,11,opt,name=bankLogo,proto3" json:"bankLogo,omitempty"`
	BankPublishName      string   `protobuf:"bytes,12,opt,name=bankPublishName,proto3" json:"bankPublishName,omitempty"`
	UrlDirectLinkBank    string   `protobuf:"bytes,13,opt,name=urlDirectLinkBank,proto3" json:"urlDirectLinkBank,omitempty"`
	UrlDeposit           string   `protobuf:"bytes,14,opt,name=urlDeposit,proto3" json:"urlDeposit,omitempty"`
	BackgroundSmall      string   `protobuf:"bytes,15,opt,name=backgroundSmall,proto3" json:"backgroundSmall,omitempty"`
	BackgroundLarge      string   `protobuf:"bytes,16,opt,name=backgroundLarge,proto3" json:"backgroundLarge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BankLinkDetail) Reset()         { *m = BankLinkDetail{} }
func (m *BankLinkDetail) String() string { return proto.CompactTextString(m) }
func (*BankLinkDetail) ProtoMessage()    {}
func (*BankLinkDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_bank_c5b0f883540c41cb, []int{2}
}
func (m *BankLinkDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankLinkDetail.Unmarshal(m, b)
}
func (m *BankLinkDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankLinkDetail.Marshal(b, m, deterministic)
}
func (dst *BankLinkDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankLinkDetail.Merge(dst, src)
}
func (m *BankLinkDetail) XXX_Size() int {
	return xxx_messageInfo_BankLinkDetail.Size(m)
}
func (m *BankLinkDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_BankLinkDetail.DiscardUnknown(m)
}

var xxx_messageInfo_BankLinkDetail proto.InternalMessageInfo

func (m *BankLinkDetail) GetLinkId() int64 {
	if m != nil {
		return m.LinkId
	}
	return 0
}

func (m *BankLinkDetail) GetCardNumber() string {
	if m != nil {
		return m.CardNumber
	}
	return ""
}

func (m *BankLinkDetail) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

func (m *BankLinkDetail) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *BankLinkDetail) GetGpayUserID() string {
	if m != nil {
		return m.GpayUserID
	}
	return ""
}

func (m *BankLinkDetail) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *BankLinkDetail) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *BankLinkDetail) GetBankCode() string {
	if m != nil {
		return m.BankCode
	}
	return ""
}

func (m *BankLinkDetail) GetGPayBankCode() string {
	if m != nil {
		return m.GPayBankCode
	}
	return ""
}

func (m *BankLinkDetail) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *BankLinkDetail) GetBankLogo() string {
	if m != nil {
		return m.BankLogo
	}
	return ""
}

func (m *BankLinkDetail) GetBankPublishName() string {
	if m != nil {
		return m.BankPublishName
	}
	return ""
}

func (m *BankLinkDetail) GetUrlDirectLinkBank() string {
	if m != nil {
		return m.UrlDirectLinkBank
	}
	return ""
}

func (m *BankLinkDetail) GetUrlDeposit() string {
	if m != nil {
		return m.UrlDeposit
	}
	return ""
}

func (m *BankLinkDetail) GetBackgroundSmall() string {
	if m != nil {
		return m.BackgroundSmall
	}
	return ""
}

func (m *BankLinkDetail) GetBackgroundLarge() string {
	if m != nil {
		return m.BackgroundLarge
	}
	return ""
}

type BankLinkInfoRequest struct {
	LinkID               string   `protobuf:"bytes,1,opt,name=linkID,proto3" json:"linkID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BankLinkInfoRequest) Reset()         { *m = BankLinkInfoRequest{} }
func (m *BankLinkInfoRequest) String() string { return proto.CompactTextString(m) }
func (*BankLinkInfoRequest) ProtoMessage()    {}
func (*BankLinkInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bank_c5b0f883540c41cb, []int{3}
}
func (m *BankLinkInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankLinkInfoRequest.Unmarshal(m, b)
}
func (m *BankLinkInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankLinkInfoRequest.Marshal(b, m, deterministic)
}
func (dst *BankLinkInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankLinkInfoRequest.Merge(dst, src)
}
func (m *BankLinkInfoRequest) XXX_Size() int {
	return xxx_messageInfo_BankLinkInfoRequest.Size(m)
}
func (m *BankLinkInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BankLinkInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BankLinkInfoRequest proto.InternalMessageInfo

func (m *BankLinkInfoRequest) GetLinkID() string {
	if m != nil {
		return m.LinkID
	}
	return ""
}

type BankLinkInfoResponse struct {
	BankLinkDetail       *BankLinkDetail `protobuf:"bytes,1,opt,name=BankLinkDetail,proto3" json:"BankLinkDetail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BankLinkInfoResponse) Reset()         { *m = BankLinkInfoResponse{} }
func (m *BankLinkInfoResponse) String() string { return proto.CompactTextString(m) }
func (*BankLinkInfoResponse) ProtoMessage()    {}
func (*BankLinkInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bank_c5b0f883540c41cb, []int{4}
}
func (m *BankLinkInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankLinkInfoResponse.Unmarshal(m, b)
}
func (m *BankLinkInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankLinkInfoResponse.Marshal(b, m, deterministic)
}
func (dst *BankLinkInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankLinkInfoResponse.Merge(dst, src)
}
func (m *BankLinkInfoResponse) XXX_Size() int {
	return xxx_messageInfo_BankLinkInfoResponse.Size(m)
}
func (m *BankLinkInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BankLinkInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BankLinkInfoResponse proto.InternalMessageInfo

func (m *BankLinkInfoResponse) GetBankLinkDetail() *BankLinkDetail {
	if m != nil {
		return m.BankLinkDetail
	}
	return nil
}

type BankUnlinkRequest struct {
	LinkId               int64    `protobuf:"varint,1,opt,name=linkId,proto3" json:"linkId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BankUnlinkRequest) Reset()         { *m = BankUnlinkRequest{} }
func (m *BankUnlinkRequest) String() string { return proto.CompactTextString(m) }
func (*BankUnlinkRequest) ProtoMessage()    {}
func (*BankUnlinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bank_c5b0f883540c41cb, []int{5}
}
func (m *BankUnlinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankUnlinkRequest.Unmarshal(m, b)
}
func (m *BankUnlinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankUnlinkRequest.Marshal(b, m, deterministic)
}
func (dst *BankUnlinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankUnlinkRequest.Merge(dst, src)
}
func (m *BankUnlinkRequest) XXX_Size() int {
	return xxx_messageInfo_BankUnlinkRequest.Size(m)
}
func (m *BankUnlinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BankUnlinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BankUnlinkRequest proto.InternalMessageInfo

func (m *BankUnlinkRequest) GetLinkId() int64 {
	if m != nil {
		return m.LinkId
	}
	return 0
}

type BankUnlinkResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BankUnlinkResponse) Reset()         { *m = BankUnlinkResponse{} }
func (m *BankUnlinkResponse) String() string { return proto.CompactTextString(m) }
func (*BankUnlinkResponse) ProtoMessage()    {}
func (*BankUnlinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bank_c5b0f883540c41cb, []int{6}
}
func (m *BankUnlinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankUnlinkResponse.Unmarshal(m, b)
}
func (m *BankUnlinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankUnlinkResponse.Marshal(b, m, deterministic)
}
func (dst *BankUnlinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankUnlinkResponse.Merge(dst, src)
}
func (m *BankUnlinkResponse) XXX_Size() int {
	return xxx_messageInfo_BankUnlinkResponse.Size(m)
}
func (m *BankUnlinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BankUnlinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BankUnlinkResponse proto.InternalMessageInfo

func (m *BankUnlinkResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type IBFTInquiryRequest struct {
	AccountNo            string   `protobuf:"bytes,1,opt,name=accountNo,proto3" json:"accountNo,omitempty"`
	IbftCode             string   `protobuf:"bytes,2,opt,name=ibftCode,proto3" json:"ibftCode,omitempty"`
	CardNo               string   `protobuf:"bytes,3,opt,name=cardNo,proto3" json:"cardNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IBFTInquiryRequest) Reset()         { *m = IBFTInquiryRequest{} }
func (m *IBFTInquiryRequest) String() string { return proto.CompactTextString(m) }
func (*IBFTInquiryRequest) ProtoMessage()    {}
func (*IBFTInquiryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bank_c5b0f883540c41cb, []int{7}
}
func (m *IBFTInquiryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IBFTInquiryRequest.Unmarshal(m, b)
}
func (m *IBFTInquiryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IBFTInquiryRequest.Marshal(b, m, deterministic)
}
func (dst *IBFTInquiryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IBFTInquiryRequest.Merge(dst, src)
}
func (m *IBFTInquiryRequest) XXX_Size() int {
	return xxx_messageInfo_IBFTInquiryRequest.Size(m)
}
func (m *IBFTInquiryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IBFTInquiryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IBFTInquiryRequest proto.InternalMessageInfo

func (m *IBFTInquiryRequest) GetAccountNo() string {
	if m != nil {
		return m.AccountNo
	}
	return ""
}

func (m *IBFTInquiryRequest) GetIbftCode() string {
	if m != nil {
		return m.IbftCode
	}
	return ""
}

func (m *IBFTInquiryRequest) GetCardNo() string {
	if m != nil {
		return m.CardNo
	}
	return ""
}

type IBFTInquiryResponse struct {
	FullName             string   `protobuf:"bytes,1,opt,name=fullName,proto3" json:"fullName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IBFTInquiryResponse) Reset()         { *m = IBFTInquiryResponse{} }
func (m *IBFTInquiryResponse) String() string { return proto.CompactTextString(m) }
func (*IBFTInquiryResponse) ProtoMessage()    {}
func (*IBFTInquiryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bank_c5b0f883540c41cb, []int{8}
}
func (m *IBFTInquiryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IBFTInquiryResponse.Unmarshal(m, b)
}
func (m *IBFTInquiryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IBFTInquiryResponse.Marshal(b, m, deterministic)
}
func (dst *IBFTInquiryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IBFTInquiryResponse.Merge(dst, src)
}
func (m *IBFTInquiryResponse) XXX_Size() int {
	return xxx_messageInfo_IBFTInquiryResponse.Size(m)
}
func (m *IBFTInquiryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IBFTInquiryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IBFTInquiryResponse proto.InternalMessageInfo

func (m *IBFTInquiryResponse) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

type BankRetrieveOrderReq struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	BankCode             string   `protobuf:"bytes,2,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BankRetrieveOrderReq) Reset()         { *m = BankRetrieveOrderReq{} }
func (m *BankRetrieveOrderReq) String() string { return proto.CompactTextString(m) }
func (*BankRetrieveOrderReq) ProtoMessage()    {}
func (*BankRetrieveOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bank_c5b0f883540c41cb, []int{9}
}
func (m *BankRetrieveOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankRetrieveOrderReq.Unmarshal(m, b)
}
func (m *BankRetrieveOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankRetrieveOrderReq.Marshal(b, m, deterministic)
}
func (dst *BankRetrieveOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankRetrieveOrderReq.Merge(dst, src)
}
func (m *BankRetrieveOrderReq) XXX_Size() int {
	return xxx_messageInfo_BankRetrieveOrderReq.Size(m)
}
func (m *BankRetrieveOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BankRetrieveOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_BankRetrieveOrderReq proto.InternalMessageInfo

func (m *BankRetrieveOrderReq) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *BankRetrieveOrderReq) GetBankCode() string {
	if m != nil {
		return m.BankCode
	}
	return ""
}

type BankRetrieveOrderRes struct {
	Amount               int64    `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	BankTransactionId    string   `protobuf:"bytes,3,opt,name=bank_transaction_id,json=bankTransactionId,proto3" json:"bank_transaction_id,omitempty"`
	ErrorCode            string   `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message              string   `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	BankCode             string   `protobuf:"bytes,6,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	GpayBankCode         string   `protobuf:"bytes,7,opt,name=gpay_bank_code,json=gpayBankCode,proto3" json:"gpay_bank_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BankRetrieveOrderRes) Reset()         { *m = BankRetrieveOrderRes{} }
func (m *BankRetrieveOrderRes) String() string { return proto.CompactTextString(m) }
func (*BankRetrieveOrderRes) ProtoMessage()    {}
func (*BankRetrieveOrderRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_bank_c5b0f883540c41cb, []int{10}
}
func (m *BankRetrieveOrderRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankRetrieveOrderRes.Unmarshal(m, b)
}
func (m *BankRetrieveOrderRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankRetrieveOrderRes.Marshal(b, m, deterministic)
}
func (dst *BankRetrieveOrderRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankRetrieveOrderRes.Merge(dst, src)
}
func (m *BankRetrieveOrderRes) XXX_Size() int {
	return xxx_messageInfo_BankRetrieveOrderRes.Size(m)
}
func (m *BankRetrieveOrderRes) XXX_DiscardUnknown() {
	xxx_messageInfo_BankRetrieveOrderRes.DiscardUnknown(m)
}

var xxx_messageInfo_BankRetrieveOrderRes proto.InternalMessageInfo

func (m *BankRetrieveOrderRes) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *BankRetrieveOrderRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *BankRetrieveOrderRes) GetBankTransactionId() string {
	if m != nil {
		return m.BankTransactionId
	}
	return ""
}

func (m *BankRetrieveOrderRes) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *BankRetrieveOrderRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BankRetrieveOrderRes) GetBankCode() string {
	if m != nil {
		return m.BankCode
	}
	return ""
}

func (m *BankRetrieveOrderRes) GetGpayBankCode() string {
	if m != nil {
		return m.GpayBankCode
	}
	return ""
}

type GetBanksReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBanksReq) Reset()         { *m = GetBanksReq{} }
func (m *GetBanksReq) String() string { return proto.CompactTextString(m) }
func (*GetBanksReq) ProtoMessage()    {}
func (*GetBanksReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bank_c5b0f883540c41cb, []int{11}
}
func (m *GetBanksReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBanksReq.Unmarshal(m, b)
}
func (m *GetBanksReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBanksReq.Marshal(b, m, deterministic)
}
func (dst *GetBanksReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBanksReq.Merge(dst, src)
}
func (m *GetBanksReq) XXX_Size() int {
	return xxx_messageInfo_GetBanksReq.Size(m)
}
func (m *GetBanksReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBanksReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetBanksReq proto.InternalMessageInfo

type Bank struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BankName             string   `protobuf:"bytes,2,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	GpayBankCode         string   `protobuf:"bytes,3,opt,name=gpay_bank_code,json=gpayBankCode,proto3" json:"gpay_bank_code,omitempty"`
	Provider             string   `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	ShortNameByNapas     string   `protobuf:"bytes,5,opt,name=short_name_by_napas,json=shortNameByNapas,proto3" json:"short_name_by_napas,omitempty"`
	ShortNameByGpay      string   `protobuf:"bytes,6,opt,name=short_name_by_gpay,json=shortNameByGpay,proto3" json:"short_name_by_gpay,omitempty"`
	PublishName          string   `protobuf:"bytes,7,opt,name=publish_name,json=publishName,proto3" json:"publish_name,omitempty"`
	BankBin              string   `protobuf:"bytes,8,opt,name=bank_bin,json=bankBin,proto3" json:"bank_bin,omitempty"`
	Status               string   `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime           int64    `protobuf:"varint,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Logo                 string   `protobuf:"bytes,11,opt,name=logo,proto3" json:"logo,omitempty"`
	BaseUrl              string   `protobuf:"bytes,12,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	UrlDirectLinkBank    string   `protobuf:"bytes,13,opt,name=url_direct_link_bank,json=urlDirectLinkBank,proto3" json:"url_direct_link_bank,omitempty"`
	UrlDeposit           string   `protobuf:"bytes,14,opt,name=url_deposit,json=urlDeposit,proto3" json:"url_deposit,omitempty"`
	BackgroundLarge      string   `protobuf:"bytes,15,opt,name=background_large,json=backgroundLarge,proto3" json:"background_large,omitempty"`
	BackgroundSmall      string   `protobuf:"bytes,16,opt,name=background_small,json=backgroundSmall,proto3" json:"background_small,omitempty"`
	MinFeeCharge         int64    `protobuf:"varint,17,opt,name=min_fee_charge,json=minFeeCharge,proto3" json:"min_fee_charge,omitempty"`
	IbftStatus           string   `protobuf:"bytes,18,opt,name=ibft_status,json=ibftStatus,proto3" json:"ibft_status,omitempty"`
	SortOrder            int64    `protobuf:"varint,19,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bank) Reset()         { *m = Bank{} }
func (m *Bank) String() string { return proto.CompactTextString(m) }
func (*Bank) ProtoMessage()    {}
func (*Bank) Descriptor() ([]byte, []int) {
	return fileDescriptor_bank_c5b0f883540c41cb, []int{12}
}
func (m *Bank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bank.Unmarshal(m, b)
}
func (m *Bank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bank.Marshal(b, m, deterministic)
}
func (dst *Bank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bank.Merge(dst, src)
}
func (m *Bank) XXX_Size() int {
	return xxx_messageInfo_Bank.Size(m)
}
func (m *Bank) XXX_DiscardUnknown() {
	xxx_messageInfo_Bank.DiscardUnknown(m)
}

var xxx_messageInfo_Bank proto.InternalMessageInfo

func (m *Bank) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Bank) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

func (m *Bank) GetGpayBankCode() string {
	if m != nil {
		return m.GpayBankCode
	}
	return ""
}

func (m *Bank) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *Bank) GetShortNameByNapas() string {
	if m != nil {
		return m.ShortNameByNapas
	}
	return ""
}

func (m *Bank) GetShortNameByGpay() string {
	if m != nil {
		return m.ShortNameByGpay
	}
	return ""
}

func (m *Bank) GetPublishName() string {
	if m != nil {
		return m.PublishName
	}
	return ""
}

func (m *Bank) GetBankBin() string {
	if m != nil {
		return m.BankBin
	}
	return ""
}

func (m *Bank) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Bank) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Bank) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *Bank) GetBaseUrl() string {
	if m != nil {
		return m.BaseUrl
	}
	return ""
}

func (m *Bank) GetUrlDirectLinkBank() string {
	if m != nil {
		return m.UrlDirectLinkBank
	}
	return ""
}

func (m *Bank) GetUrlDeposit() string {
	if m != nil {
		return m.UrlDeposit
	}
	return ""
}

func (m *Bank) GetBackgroundLarge() string {
	if m != nil {
		return m.BackgroundLarge
	}
	return ""
}

func (m *Bank) GetBackgroundSmall() string {
	if m != nil {
		return m.BackgroundSmall
	}
	return ""
}

func (m *Bank) GetMinFeeCharge() int64 {
	if m != nil {
		return m.MinFeeCharge
	}
	return 0
}

func (m *Bank) GetIbftStatus() string {
	if m != nil {
		return m.IbftStatus
	}
	return ""
}

func (m *Bank) GetSortOrder() int64 {
	if m != nil {
		return m.SortOrder
	}
	return 0
}

type GetBanksRes struct {
	Data                 []*Bank  `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBanksRes) Reset()         { *m = GetBanksRes{} }
func (m *GetBanksRes) String() string { return proto.CompactTextString(m) }
func (*GetBanksRes) ProtoMessage()    {}
func (*GetBanksRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_bank_c5b0f883540c41cb, []int{13}
}
func (m *GetBanksRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBanksRes.Unmarshal(m, b)
}
func (m *GetBanksRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBanksRes.Marshal(b, m, deterministic)
}
func (dst *GetBanksRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBanksRes.Merge(dst, src)
}
func (m *GetBanksRes) XXX_Size() int {
	return xxx_messageInfo_GetBanksRes.Size(m)
}
func (m *GetBanksRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBanksRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetBanksRes proto.InternalMessageInfo

func (m *GetBanksRes) GetData() []*Bank {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*BankLinkListRequest)(nil), "order_system.BankLinkListRequest")
	proto.RegisterType((*BankLinkListResponse)(nil), "order_system.BankLinkListResponse")
	proto.RegisterType((*BankLinkDetail)(nil), "order_system.BankLinkDetail")
	proto.RegisterType((*BankLinkInfoRequest)(nil), "order_system.BankLinkInfoRequest")
	proto.RegisterType((*BankLinkInfoResponse)(nil), "order_system.BankLinkInfoResponse")
	proto.RegisterType((*BankUnlinkRequest)(nil), "order_system.BankUnlinkRequest")
	proto.RegisterType((*BankUnlinkResponse)(nil), "order_system.BankUnlinkResponse")
	proto.RegisterType((*IBFTInquiryRequest)(nil), "order_system.IBFTInquiryRequest")
	proto.RegisterType((*IBFTInquiryResponse)(nil), "order_system.IBFTInquiryResponse")
	proto.RegisterType((*BankRetrieveOrderReq)(nil), "order_system.BankRetrieveOrderReq")
	proto.RegisterType((*BankRetrieveOrderRes)(nil), "order_system.BankRetrieveOrderRes")
	proto.RegisterType((*GetBanksReq)(nil), "order_system.GetBanksReq")
	proto.RegisterType((*Bank)(nil), "order_system.Bank")
	proto.RegisterType((*GetBanksRes)(nil), "order_system.GetBanksRes")
}

func init() { proto.RegisterFile("order_system/bank.proto", fileDescriptor_bank_c5b0f883540c41cb) }

var fileDescriptor_bank_c5b0f883540c41cb = []byte{
	// 913 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x56, 0xdd, 0x6e, 0xdb, 0x46,
	0x13, 0x85, 0x6c, 0xc5, 0xb2, 0x46, 0xb2, 0x6c, 0xaf, 0x82, 0xef, 0x63, 0xda, 0xa4, 0x71, 0x09,
	0xa3, 0x70, 0x91, 0xc4, 0x41, 0x5b, 0xe4, 0xae, 0x57, 0x8a, 0x91, 0x40, 0x80, 0xe1, 0x06, 0x8c,
	0x7d, 0x57, 0x80, 0x58, 0x91, 0x2b, 0x79, 0x61, 0x92, 0x4b, 0xef, 0x2e, 0x03, 0xe8, 0x01, 0xfa,
	0x2e, 0x7d, 0xc0, 0x3e, 0x40, 0x31, 0xb3, 0xcb, 0xf0, 0xc7, 0x0e, 0x7a, 0x61, 0x80, 0x73, 0x66,
	0x76, 0x66, 0x76, 0xf6, 0xcc, 0xb1, 0xe0, 0xff, 0x4a, 0xa7, 0x42, 0xc7, 0x66, 0x6b, 0xac, 0xc8,
	0xdf, 0xae, 0x78, 0x71, 0x77, 0x5e, 0x6a, 0x65, 0x15, 0x9b, 0xb6, 0x1d, 0xe1, 0x3b, 0x98, 0x2f,
	0x78, 0x71, 0x77, 0x29, 0xf1, 0xcf, 0xd8, 0x48, 0xdc, 0x57, 0xc2, 0x58, 0xf6, 0x03, 0xc0, 0xa6,
	0xe4, 0xdb, 0x1b, 0x23, 0xf4, 0xf2, 0x22, 0x18, 0x9c, 0x0c, 0xce, 0xc6, 0x51, 0x0b, 0x09, 0xaf,
	0xe1, 0x69, 0xf7, 0x98, 0x29, 0x55, 0x61, 0x04, 0xfb, 0x1d, 0x00, 0xb1, 0x0b, 0x61, 0xb9, 0xcc,
	0x82, 0xc1, 0xc9, 0xee, 0xd9, 0xe4, 0xd7, 0xe7, 0xe7, 0xed, 0x8a, 0xe7, 0xf5, 0x39, 0x17, 0x13,
	0xb5, 0xe2, 0xc3, 0xbf, 0x87, 0x30, 0xeb, 0xba, 0xd9, 0xff, 0x60, 0x2f, 0x93, 0xc5, 0xdd, 0x32,
	0xa5, 0x26, 0x76, 0x23, 0x6f, 0x61, 0x83, 0x09, 0xd7, 0xe9, 0x55, 0x95, 0xaf, 0x84, 0x0e, 0x76,
	0x5c, 0x83, 0x0d, 0xc2, 0x4e, 0xe1, 0x80, 0x27, 0x89, 0xaa, 0x0a, 0xeb, 0x43, 0x76, 0x29, 0xa4,
	0x0b, 0xb2, 0xef, 0x60, 0x7f, 0x5d, 0x65, 0xd9, 0x15, 0xcf, 0x45, 0x30, 0xa4, 0x80, 0xaf, 0x76,
	0x6f, 0x04, 0x4f, 0xfa, 0x23, 0x60, 0x27, 0x30, 0x29, 0x6f, 0x55, 0x21, 0x7c, 0xfe, 0x3d, 0x0a,
	0x68, 0x43, 0x98, 0xbd, 0xd4, 0xea, 0x8b, 0x4c, 0x85, 0x0e, 0x46, 0x2e, 0x7b, 0x6d, 0xa3, 0x0f,
	0xdf, 0xe4, 0xbd, 0x4a, 0x45, 0xb0, 0xef, 0x7c, 0xb5, 0xcd, 0x42, 0x98, 0x6e, 0x3e, 0xf1, 0xed,
	0xa2, 0xf6, 0x8f, 0xc9, 0xdf, 0xc1, 0x70, 0x2e, 0xc6, 0x72, 0x5b, 0x99, 0x00, 0xc8, 0xeb, 0xad,
	0x3a, 0xef, 0xa5, 0xda, 0xa8, 0x60, 0xd2, 0xe4, 0x45, 0x9b, 0x9d, 0xc1, 0x21, 0x7e, 0x7f, 0xaa,
	0x56, 0x99, 0x34, 0xb7, 0x74, 0xe9, 0x29, 0x85, 0xf4, 0x61, 0xf6, 0x1a, 0x8e, 0x2b, 0x9d, 0x5d,
	0x48, 0x2d, 0x12, 0x8b, 0x8f, 0x81, 0x65, 0x83, 0x03, 0x8a, 0x7d, 0xe8, 0xc0, 0x49, 0x21, 0x28,
	0x4a, 0x65, 0xa4, 0x0d, 0x66, 0x6e, 0x52, 0x0d, 0xe2, 0xea, 0x26, 0x77, 0x1b, 0xad, 0xaa, 0x22,
	0xfd, 0x9c, 0xf3, 0x2c, 0x0b, 0x0e, 0xeb, 0xba, 0x1d, 0xb8, 0x1b, 0x79, 0xc9, 0xf5, 0x46, 0x04,
	0x47, 0xfd, 0x48, 0x82, 0xc3, 0x37, 0x0d, 0x6f, 0x97, 0xc5, 0x5a, 0xd5, 0xbc, 0xad, 0xe9, 0x52,
	0x73, 0xd6, 0x5b, 0xe1, 0x9f, 0x0d, 0x5f, 0x5d, 0xb8, 0xe7, 0xeb, 0x45, 0x9f, 0x70, 0x74, 0xee,
	0xbf, 0x38, 0xdb, 0x3b, 0x13, 0xbe, 0x82, 0x63, 0x44, 0x6e, 0x0a, 0xac, 0xd6, 0x6f, 0xa5, 0xc7,
	0xdc, 0xf0, 0x35, 0xb0, 0x76, 0xb0, 0x6f, 0xa4, 0x79, 0xcf, 0x41, 0xfb, 0x3d, 0xc3, 0x35, 0xb0,
	0xe5, 0xe2, 0xc3, 0xf5, 0xb2, 0xb8, 0xaf, 0xa4, 0xde, 0xd6, 0xb9, 0x9f, 0xc3, 0xb8, 0x26, 0xb2,
	0xf2, 0x07, 0x1a, 0x00, 0x39, 0x20, 0x57, 0x6b, 0x4b, 0xdc, 0x71, 0x9b, 0xf1, 0xd5, 0xc6, 0x3a,
	0xb4, 0x25, 0xca, 0x2f, 0x84, 0xb7, 0xc2, 0x5f, 0x60, 0xde, 0xa9, 0xe3, 0xdb, 0x6a, 0x2f, 0xc8,
	0xa0, 0xbb, 0x20, 0xe1, 0x95, 0x9b, 0x69, 0x24, 0xac, 0x96, 0xe2, 0x8b, 0xf8, 0x03, 0x07, 0x16,
	0x89, 0x7b, 0xf6, 0x0c, 0xf6, 0xdd, 0xf0, 0x64, 0xea, 0xcf, 0x8c, 0xc8, 0x5e, 0xa6, 0xec, 0x7b,
	0x18, 0x23, 0xd5, 0xe2, 0xa4, 0xd5, 0x5a, 0x4d, 0xfb, 0xf0, 0x9f, 0xc1, 0xa3, 0x09, 0x0d, 0xf6,
	0xcc, 0x73, 0xbc, 0x5b, 0x3d, 0x49, 0x67, 0xb1, 0x00, 0x46, 0xa6, 0x4a, 0x12, 0x61, 0x0c, 0xe5,
	0xda, 0x8f, 0x6a, 0x93, 0x9d, 0xc3, 0x9c, 0xea, 0x58, 0xcd, 0x0b, 0xc3, 0x13, 0x2b, 0x55, 0x81,
	0xdd, 0xb8, 0x2b, 0x1f, 0xa3, 0xeb, 0xba, 0xf1, 0x2c, 0x53, 0xf6, 0x02, 0x40, 0x68, 0xad, 0xb4,
	0x6b, 0xcc, 0x29, 0xc1, 0x98, 0x10, 0x1a, 0x5a, 0x00, 0xa3, 0x5c, 0x18, 0xc3, 0x37, 0xc2, 0xeb,
	0x40, 0x6d, 0x76, 0x2f, 0xb4, 0xd7, 0xdb, 0xe3, 0x53, 0x98, 0xa1, 0x5e, 0xc4, 0x4d, 0xc4, 0xc8,
	0x6f, 0x72, 0xd9, 0x6c, 0x72, 0x78, 0x00, 0x93, 0x8f, 0xc2, 0xa2, 0x69, 0x22, 0x71, 0x1f, 0xfe,
	0xf5, 0x04, 0x86, 0xb4, 0x55, 0x33, 0xd8, 0x91, 0x35, 0x77, 0x76, 0x64, 0x33, 0xbb, 0x02, 0xdf,
	0xa2, 0x35, 0x3b, 0x5a, 0xd8, 0x87, 0xa5, 0x76, 0x1f, 0x96, 0xea, 0x08, 0xd2, 0xb0, 0x27, 0x48,
	0x6f, 0x60, 0x6e, 0x6e, 0x95, 0xb6, 0x94, 0x3f, 0x5e, 0x6d, 0xe3, 0x82, 0x97, 0xdc, 0xf8, 0xfb,
	0x1e, 0x91, 0x0b, 0x2b, 0x2d, 0xb6, 0x57, 0x88, 0xb3, 0x57, 0xc0, 0xba, 0xe1, 0x58, 0xc8, 0x4f,
	0xe0, 0xb0, 0x15, 0xfd, 0xb1, 0xe4, 0x5b, 0xf6, 0x23, 0x4c, 0x4b, 0xa7, 0x2e, 0xae, 0xfb, 0x91,
	0xd7, 0xca, 0x96, 0xe2, 0x3c, 0x73, 0xba, 0x15, 0xaf, 0x64, 0xe1, 0xf5, 0x70, 0x84, 0xf6, 0x42,
	0x16, 0xad, 0xd5, 0x18, 0x77, 0xa4, 0xee, 0x25, 0x4c, 0x12, 0x2d, 0xb8, 0x15, 0xb1, 0x95, 0xb9,
	0x20, 0x1d, 0xdc, 0x8d, 0xc0, 0x41, 0xd7, 0x32, 0x17, 0x8c, 0xc1, 0x30, 0x6b, 0x74, 0x90, 0xbe,
	0x5d, 0x1d, 0x23, 0xe2, 0x4a, 0x67, 0x5e, 0xfc, 0x46, 0x68, 0xdf, 0xe8, 0x8c, 0xbd, 0x85, 0xa7,
	0x95, 0xce, 0xe2, 0x94, 0xc4, 0x2d, 0xc6, 0xed, 0xa4, 0x71, 0x7e, 0x5b, 0xf7, 0x5e, 0xc2, 0x84,
	0x0e, 0x7c, 0x53, 0xf8, 0x7e, 0x86, 0xa3, 0x46, 0xb7, 0xe2, 0x8c, 0xf4, 0xec, 0xf0, 0x51, 0x3d,
	0xeb, 0x85, 0x1a, 0x12, 0xc9, 0xa3, 0xc7, 0x45, 0xf2, 0x14, 0x66, 0xb9, 0x2c, 0xe2, 0xb5, 0x10,
	0x71, 0x72, 0x4b, 0x39, 0x8f, 0xe9, 0xea, 0xd3, 0x5c, 0x16, 0x1f, 0x84, 0x78, 0x4f, 0x18, 0x36,
	0x87, 0x4b, 0x1f, 0xfb, 0xd1, 0x31, 0xd7, 0x1c, 0x42, 0x9f, 0xdd, 0xf8, 0x5e, 0x00, 0x18, 0x7c,
	0x40, 0xda, 0xcd, 0x60, 0x4e, 0x29, 0xc6, 0x88, 0xd0, 0xde, 0x85, 0xef, 0xda, 0xb4, 0x34, 0xec,
	0x27, 0x18, 0xa6, 0xdc, 0x72, 0xff, 0x2f, 0x9d, 0x3d, 0x94, 0xc7, 0x88, 0xfc, 0xab, 0x3d, 0xfa,
	0x91, 0xf1, 0xdb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x54, 0xfe, 0x33, 0x7f, 0x08, 0x00,
	0x00,
}
