// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order_system/fee.proto

package order_system

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CheckMerchantQuotaAndFeeReq_VAType int32

const (
	CheckMerchantQuotaAndFeeReq_OPTIONAL CheckMerchantQuotaAndFeeReq_VAType = 0
	CheckMerchantQuotaAndFeeReq_ONETIME  CheckMerchantQuotaAndFeeReq_VAType = 1
	CheckMerchantQuotaAndFeeReq_MANYTIME CheckMerchantQuotaAndFeeReq_VAType = 2
)

var CheckMerchantQuotaAndFeeReq_VAType_name = map[int32]string{
	0: "OPTIONAL",
	1: "ONETIME",
	2: "MANYTIME",
}
var CheckMerchantQuotaAndFeeReq_VAType_value = map[string]int32{
	"OPTIONAL": 0,
	"ONETIME":  1,
	"MANYTIME": 2,
}

func (x CheckMerchantQuotaAndFeeReq_VAType) String() string {
	return proto.EnumName(CheckMerchantQuotaAndFeeReq_VAType_name, int32(x))
}
func (CheckMerchantQuotaAndFeeReq_VAType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fee_0bee5bf2415d69f0, []int{0, 0}
}

type CheckMerchantQuotaAndFeeRes_FeeMethod int32

const (
	CheckMerchantQuotaAndFeeRes_FEE_NOW        CheckMerchantQuotaAndFeeRes_FeeMethod = 0
	CheckMerchantQuotaAndFeeRes_FEE_LATER      CheckMerchantQuotaAndFeeRes_FeeMethod = 1
	CheckMerchantQuotaAndFeeRes_FEE_END_PERIOD CheckMerchantQuotaAndFeeRes_FeeMethod = 3
)

var CheckMerchantQuotaAndFeeRes_FeeMethod_name = map[int32]string{
	0: "FEE_NOW",
	1: "FEE_LATER",
	3: "FEE_END_PERIOD",
}
var CheckMerchantQuotaAndFeeRes_FeeMethod_value = map[string]int32{
	"FEE_NOW":        0,
	"FEE_LATER":      1,
	"FEE_END_PERIOD": 3,
}

func (x CheckMerchantQuotaAndFeeRes_FeeMethod) String() string {
	return proto.EnumName(CheckMerchantQuotaAndFeeRes_FeeMethod_name, int32(x))
}
func (CheckMerchantQuotaAndFeeRes_FeeMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fee_0bee5bf2415d69f0, []int{1, 0}
}

type CheckMerchantQuotaAndFeeReq struct {
	Amount               int64                              `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	ServiceType          string                             `protobuf:"bytes,2,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	TransType            string                             `protobuf:"bytes,3,opt,name=trans_type,json=transType,proto3" json:"trans_type,omitempty"`
	SubTransType         string                             `protobuf:"bytes,4,opt,name=sub_trans_type,json=subTransType,proto3" json:"sub_trans_type,omitempty"`
	MerchantId           string                             `protobuf:"bytes,5,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	SourceOfFund         string                             `protobuf:"bytes,6,opt,name=source_of_fund,json=sourceOfFund,proto3" json:"source_of_fund,omitempty"`
	VaType               CheckMerchantQuotaAndFeeReq_VAType `protobuf:"varint,7,opt,name=va_type,json=vaType,proto3,enum=order_system.CheckMerchantQuotaAndFeeReq_VAType" json:"va_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *CheckMerchantQuotaAndFeeReq) Reset()         { *m = CheckMerchantQuotaAndFeeReq{} }
func (m *CheckMerchantQuotaAndFeeReq) String() string { return proto.CompactTextString(m) }
func (*CheckMerchantQuotaAndFeeReq) ProtoMessage()    {}
func (*CheckMerchantQuotaAndFeeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fee_0bee5bf2415d69f0, []int{0}
}
func (m *CheckMerchantQuotaAndFeeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckMerchantQuotaAndFeeReq.Unmarshal(m, b)
}
func (m *CheckMerchantQuotaAndFeeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckMerchantQuotaAndFeeReq.Marshal(b, m, deterministic)
}
func (dst *CheckMerchantQuotaAndFeeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckMerchantQuotaAndFeeReq.Merge(dst, src)
}
func (m *CheckMerchantQuotaAndFeeReq) XXX_Size() int {
	return xxx_messageInfo_CheckMerchantQuotaAndFeeReq.Size(m)
}
func (m *CheckMerchantQuotaAndFeeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckMerchantQuotaAndFeeReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckMerchantQuotaAndFeeReq proto.InternalMessageInfo

func (m *CheckMerchantQuotaAndFeeReq) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CheckMerchantQuotaAndFeeReq) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *CheckMerchantQuotaAndFeeReq) GetTransType() string {
	if m != nil {
		return m.TransType
	}
	return ""
}

func (m *CheckMerchantQuotaAndFeeReq) GetSubTransType() string {
	if m != nil {
		return m.SubTransType
	}
	return ""
}

func (m *CheckMerchantQuotaAndFeeReq) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *CheckMerchantQuotaAndFeeReq) GetSourceOfFund() string {
	if m != nil {
		return m.SourceOfFund
	}
	return ""
}

func (m *CheckMerchantQuotaAndFeeReq) GetVaType() CheckMerchantQuotaAndFeeReq_VAType {
	if m != nil {
		return m.VaType
	}
	return CheckMerchantQuotaAndFeeReq_OPTIONAL
}

type CheckMerchantQuotaAndFeeRes struct {
	FeeAmount            int64                                 `protobuf:"varint,1,opt,name=fee_amount,json=feeAmount,proto3" json:"fee_amount,omitempty"`
	FeeMethod            CheckMerchantQuotaAndFeeRes_FeeMethod `protobuf:"varint,2,opt,name=fee_method,json=feeMethod,proto3,enum=order_system.CheckMerchantQuotaAndFeeRes_FeeMethod" json:"fee_method,omitempty"`
	FixedFeeAmount       int64                                 `protobuf:"varint,3,opt,name=fixed_fee_amount,json=fixedFeeAmount,proto3" json:"fixed_fee_amount,omitempty"`
	RateFeeAmount        int64                                 `protobuf:"varint,4,opt,name=rate_fee_amount,json=rateFeeAmount,proto3" json:"rate_fee_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *CheckMerchantQuotaAndFeeRes) Reset()         { *m = CheckMerchantQuotaAndFeeRes{} }
func (m *CheckMerchantQuotaAndFeeRes) String() string { return proto.CompactTextString(m) }
func (*CheckMerchantQuotaAndFeeRes) ProtoMessage()    {}
func (*CheckMerchantQuotaAndFeeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_fee_0bee5bf2415d69f0, []int{1}
}
func (m *CheckMerchantQuotaAndFeeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckMerchantQuotaAndFeeRes.Unmarshal(m, b)
}
func (m *CheckMerchantQuotaAndFeeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckMerchantQuotaAndFeeRes.Marshal(b, m, deterministic)
}
func (dst *CheckMerchantQuotaAndFeeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckMerchantQuotaAndFeeRes.Merge(dst, src)
}
func (m *CheckMerchantQuotaAndFeeRes) XXX_Size() int {
	return xxx_messageInfo_CheckMerchantQuotaAndFeeRes.Size(m)
}
func (m *CheckMerchantQuotaAndFeeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckMerchantQuotaAndFeeRes.DiscardUnknown(m)
}

var xxx_messageInfo_CheckMerchantQuotaAndFeeRes proto.InternalMessageInfo

func (m *CheckMerchantQuotaAndFeeRes) GetFeeAmount() int64 {
	if m != nil {
		return m.FeeAmount
	}
	return 0
}

func (m *CheckMerchantQuotaAndFeeRes) GetFeeMethod() CheckMerchantQuotaAndFeeRes_FeeMethod {
	if m != nil {
		return m.FeeMethod
	}
	return CheckMerchantQuotaAndFeeRes_FEE_NOW
}

func (m *CheckMerchantQuotaAndFeeRes) GetFixedFeeAmount() int64 {
	if m != nil {
		return m.FixedFeeAmount
	}
	return 0
}

func (m *CheckMerchantQuotaAndFeeRes) GetRateFeeAmount() int64 {
	if m != nil {
		return m.RateFeeAmount
	}
	return 0
}

func init() {
	proto.RegisterType((*CheckMerchantQuotaAndFeeReq)(nil), "order_system.CheckMerchantQuotaAndFeeReq")
	proto.RegisterType((*CheckMerchantQuotaAndFeeRes)(nil), "order_system.CheckMerchantQuotaAndFeeRes")
	proto.RegisterEnum("order_system.CheckMerchantQuotaAndFeeReq_VAType", CheckMerchantQuotaAndFeeReq_VAType_name, CheckMerchantQuotaAndFeeReq_VAType_value)
	proto.RegisterEnum("order_system.CheckMerchantQuotaAndFeeRes_FeeMethod", CheckMerchantQuotaAndFeeRes_FeeMethod_name, CheckMerchantQuotaAndFeeRes_FeeMethod_value)
}

func init() { proto.RegisterFile("order_system/fee.proto", fileDescriptor_fee_0bee5bf2415d69f0) }

var fileDescriptor_fee_0bee5bf2415d69f0 = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x51, 0x8b, 0x9b, 0x40,
	0x14, 0x85, 0xd7, 0x64, 0x6b, 0xea, 0x4d, 0xd6, 0xca, 0x3c, 0x2c, 0x81, 0x52, 0x9a, 0x86, 0x52,
	0xf2, 0x64, 0xdb, 0xdd, 0xc7, 0x3e, 0x49, 0x57, 0x41, 0xd8, 0xe8, 0x56, 0xa4, 0xa5, 0x4f, 0x83,
	0x71, 0xae, 0x24, 0x14, 0x9d, 0x74, 0x66, 0x0c, 0xcd, 0xaf, 0xe9, 0x7f, 0xeb, 0x2f, 0x29, 0x33,
	0x5a, 0xb1, 0x2f, 0xcb, 0x3e, 0xe9, 0x39, 0xf7, 0xf3, 0x9e, 0xcb, 0x41, 0xb8, 0xe6, 0x82, 0xa1,
	0xa0, 0xf2, 0x2c, 0x15, 0xd6, 0xef, 0x2b, 0x44, 0xff, 0x28, 0xb8, 0xe2, 0x64, 0x31, 0xf6, 0xd7,
	0x7f, 0x26, 0xf0, 0xf2, 0xf3, 0x1e, 0xcb, 0x1f, 0x5b, 0x14, 0xe5, 0xbe, 0x68, 0xd4, 0x97, 0x96,
	0xab, 0x22, 0x68, 0x58, 0x84, 0x98, 0xe1, 0x4f, 0x72, 0x0d, 0x76, 0x51, 0xf3, 0xb6, 0x51, 0x4b,
	0x6b, 0x65, 0x6d, 0xa6, 0x59, 0xaf, 0xc8, 0x1b, 0x58, 0x48, 0x14, 0xa7, 0x43, 0x89, 0x54, 0x9d,
	0x8f, 0xb8, 0x9c, 0xac, 0xac, 0x8d, 0x93, 0xcd, 0x7b, 0x2f, 0x3f, 0x1f, 0x91, 0xbc, 0x02, 0x50,
	0xa2, 0x68, 0x64, 0x07, 0x4c, 0x0d, 0xe0, 0x18, 0xc7, 0x8c, 0xdf, 0x82, 0x2b, 0xdb, 0x1d, 0x1d,
	0x21, 0x97, 0x06, 0x59, 0xc8, 0x76, 0x97, 0x0f, 0xd4, 0x6b, 0x98, 0xd7, 0xfd, 0x65, 0xf4, 0xc0,
	0x96, 0xcf, 0x0c, 0x02, 0xff, 0xac, 0x98, 0x99, 0x35, 0xbc, 0x15, 0x25, 0x52, 0x5e, 0xd1, 0xaa,
	0x6d, 0xd8, 0xd2, 0xee, 0xd7, 0x18, 0x37, 0xad, 0xa2, 0xb6, 0x61, 0x24, 0x86, 0xd9, 0xa9, 0xe8,
	0x52, 0x66, 0x2b, 0x6b, 0xe3, 0xde, 0x7c, 0xf0, 0xc7, 0x35, 0xf8, 0x8f, 0x54, 0xe0, 0x7f, 0x0d,
	0xf4, 0x25, 0x99, 0x7d, 0x2a, 0xf4, 0x73, 0xfd, 0x11, 0xec, 0xce, 0x21, 0x0b, 0x78, 0x9e, 0x3e,
	0xe4, 0x71, 0x9a, 0x04, 0xf7, 0xde, 0x05, 0x99, 0xc3, 0x2c, 0x4d, 0xc2, 0x3c, 0xde, 0x86, 0x9e,
	0xa5, 0x47, 0xdb, 0x20, 0xf9, 0x6e, 0xd4, 0x64, 0xfd, 0xfb, 0xd1, 0x92, 0xa5, 0x6e, 0xaa, 0x42,
	0xa4, 0xff, 0x15, 0xed, 0x54, 0x88, 0x41, 0xd7, 0x75, 0xd6, 0x8d, 0x6b, 0x54, 0x7b, 0xce, 0x4c,
	0xd3, 0xee, 0xcd, 0xed, 0x53, 0xef, 0x97, 0x7e, 0x84, 0xb8, 0x35, 0x9f, 0x9a, 0x9d, 0xdd, 0x2b,
	0xd9, 0x80, 0x57, 0x1d, 0x7e, 0x21, 0xa3, 0xa3, 0xe0, 0xa9, 0x09, 0x76, 0x8d, 0x1f, 0x0d, 0xe9,
	0xef, 0xe0, 0x85, 0x28, 0x14, 0x8e, 0xc1, 0x4b, 0x03, 0x5e, 0x69, 0x7b, 0xe0, 0xd6, 0x9f, 0xc0,
	0x19, 0x92, 0x74, 0x19, 0x51, 0x18, 0xd2, 0x24, 0xfd, 0xe6, 0x5d, 0x90, 0x2b, 0x70, 0xb4, 0xb8,
	0x0f, 0xf2, 0x30, 0xf3, 0x2c, 0x42, 0xc0, 0xd5, 0x32, 0x4c, 0xee, 0xe8, 0x43, 0x98, 0xc5, 0xe9,
	0x9d, 0x37, 0xdd, 0xd9, 0xe6, 0xdf, 0xbc, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x85, 0xe2,
	0xc6, 0xb5, 0x02, 0x00, 0x00,
}
