// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order_system/payment_gateway.proto

package order_system

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PGInitTransReq struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Amount               int64    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	MerchantCode         string   `protobuf:"bytes,4,opt,name=merchant_code,json=merchantCode,proto3" json:"merchant_code,omitempty"`
	RedirectUrl          string   `protobuf:"bytes,5,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	BankCode             string   `protobuf:"bytes,6,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PGInitTransReq) Reset()         { *m = PGInitTransReq{} }
func (m *PGInitTransReq) String() string { return proto.CompactTextString(m) }
func (*PGInitTransReq) ProtoMessage()    {}
func (*PGInitTransReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_payment_gateway_e70a716a47e994cd, []int{0}
}
func (m *PGInitTransReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PGInitTransReq.Unmarshal(m, b)
}
func (m *PGInitTransReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PGInitTransReq.Marshal(b, m, deterministic)
}
func (dst *PGInitTransReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PGInitTransReq.Merge(dst, src)
}
func (m *PGInitTransReq) XXX_Size() int {
	return xxx_messageInfo_PGInitTransReq.Size(m)
}
func (m *PGInitTransReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PGInitTransReq.DiscardUnknown(m)
}

var xxx_messageInfo_PGInitTransReq proto.InternalMessageInfo

func (m *PGInitTransReq) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *PGInitTransReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PGInitTransReq) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PGInitTransReq) GetMerchantCode() string {
	if m != nil {
		return m.MerchantCode
	}
	return ""
}

func (m *PGInitTransReq) GetRedirectUrl() string {
	if m != nil {
		return m.RedirectUrl
	}
	return ""
}

func (m *PGInitTransReq) GetBankCode() string {
	if m != nil {
		return m.BankCode
	}
	return ""
}

type PGInitTransRes struct {
	RedirectUrl          string   `protobuf:"bytes,1,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PGInitTransRes) Reset()         { *m = PGInitTransRes{} }
func (m *PGInitTransRes) String() string { return proto.CompactTextString(m) }
func (*PGInitTransRes) ProtoMessage()    {}
func (*PGInitTransRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_payment_gateway_e70a716a47e994cd, []int{1}
}
func (m *PGInitTransRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PGInitTransRes.Unmarshal(m, b)
}
func (m *PGInitTransRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PGInitTransRes.Marshal(b, m, deterministic)
}
func (dst *PGInitTransRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PGInitTransRes.Merge(dst, src)
}
func (m *PGInitTransRes) XXX_Size() int {
	return xxx_messageInfo_PGInitTransRes.Size(m)
}
func (m *PGInitTransRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PGInitTransRes.DiscardUnknown(m)
}

var xxx_messageInfo_PGInitTransRes proto.InternalMessageInfo

func (m *PGInitTransRes) GetRedirectUrl() string {
	if m != nil {
		return m.RedirectUrl
	}
	return ""
}

type PGInitOrderReq struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	BankCode             string   `protobuf:"bytes,2,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PGInitOrderReq) Reset()         { *m = PGInitOrderReq{} }
func (m *PGInitOrderReq) String() string { return proto.CompactTextString(m) }
func (*PGInitOrderReq) ProtoMessage()    {}
func (*PGInitOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_payment_gateway_e70a716a47e994cd, []int{2}
}
func (m *PGInitOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PGInitOrderReq.Unmarshal(m, b)
}
func (m *PGInitOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PGInitOrderReq.Marshal(b, m, deterministic)
}
func (dst *PGInitOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PGInitOrderReq.Merge(dst, src)
}
func (m *PGInitOrderReq) XXX_Size() int {
	return xxx_messageInfo_PGInitOrderReq.Size(m)
}
func (m *PGInitOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PGInitOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_PGInitOrderReq proto.InternalMessageInfo

func (m *PGInitOrderReq) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *PGInitOrderReq) GetBankCode() string {
	if m != nil {
		return m.BankCode
	}
	return ""
}

func (m *PGInitOrderReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PGInitOrderRes struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PGInitOrderRes) Reset()         { *m = PGInitOrderRes{} }
func (m *PGInitOrderRes) String() string { return proto.CompactTextString(m) }
func (*PGInitOrderRes) ProtoMessage()    {}
func (*PGInitOrderRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_payment_gateway_e70a716a47e994cd, []int{3}
}
func (m *PGInitOrderRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PGInitOrderRes.Unmarshal(m, b)
}
func (m *PGInitOrderRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PGInitOrderRes.Marshal(b, m, deterministic)
}
func (dst *PGInitOrderRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PGInitOrderRes.Merge(dst, src)
}
func (m *PGInitOrderRes) XXX_Size() int {
	return xxx_messageInfo_PGInitOrderRes.Size(m)
}
func (m *PGInitOrderRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PGInitOrderRes.DiscardUnknown(m)
}

var xxx_messageInfo_PGInitOrderRes proto.InternalMessageInfo

func (m *PGInitOrderRes) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*PGInitTransReq)(nil), "order_system.PGInitTransReq")
	proto.RegisterType((*PGInitTransRes)(nil), "order_system.PGInitTransRes")
	proto.RegisterType((*PGInitOrderReq)(nil), "order_system.PGInitOrderReq")
	proto.RegisterType((*PGInitOrderRes)(nil), "order_system.PGInitOrderRes")
}

func init() {
	proto.RegisterFile("order_system/payment_gateway.proto", fileDescriptor_payment_gateway_e70a716a47e994cd)
}

var fileDescriptor_payment_gateway_e70a716a47e994cd = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0xe5, 0xb4, 0x84, 0xf6, 0x08, 0x1d, 0x3c, 0xa0, 0x20, 0x96, 0x10, 0x18, 0x3a, 0xc1,
	0xd0, 0x8f, 0xc0, 0x80, 0x3a, 0x01, 0x11, 0xcc, 0x91, 0x1b, 0x9f, 0xc0, 0xa2, 0xb1, 0xc3, 0xf9,
	0x2a, 0x94, 0xaf, 0xc8, 0xa7, 0x42, 0x71, 0x1a, 0xe8, 0x9f, 0x2d, 0xf7, 0xee, 0xbd, 0xdf, 0xe9,
	0xc5, 0x90, 0x3b, 0xd2, 0x48, 0xa5, 0x6f, 0x3d, 0x63, 0x7d, 0xdf, 0xa8, 0xb6, 0x46, 0xcb, 0xe5,
	0xbb, 0x62, 0xfc, 0x56, 0xed, 0x5d, 0x43, 0x8e, 0x9d, 0x4c, 0x76, 0x3d, 0xf9, 0x8f, 0x80, 0xd9,
	0xf3, 0xe3, 0xd2, 0x1a, 0x7e, 0x25, 0x65, 0x7d, 0x81, 0x5f, 0xf2, 0x12, 0x26, 0xbd, 0xc5, 0xe8,
	0x54, 0x64, 0x62, 0x3e, 0x2d, 0x4e, 0xc3, 0xbc, 0xd4, 0x32, 0x83, 0x33, 0x8d, 0xbe, 0x22, 0xd3,
	0xb0, 0x71, 0x36, 0x8d, 0xc2, 0x76, 0x57, 0x92, 0x17, 0x10, 0xab, 0xda, 0x6d, 0x2c, 0xa7, 0xa3,
	0x4c, 0xcc, 0x47, 0xc5, 0x76, 0x92, 0x37, 0x70, 0x5e, 0x23, 0x55, 0x1f, 0xca, 0x72, 0x59, 0x39,
	0x8d, 0xe9, 0x38, 0x64, 0x93, 0x41, 0x7c, 0x70, 0x1a, 0xe5, 0x35, 0x24, 0x84, 0xda, 0x10, 0x56,
	0x5c, 0x6e, 0x68, 0x9d, 0x9e, 0xf4, 0xfc, 0x41, 0x7b, 0xa3, 0xb5, 0xbc, 0x82, 0xe9, 0x4a, 0xd9,
	0xcf, 0x9e, 0x11, 0x87, 0xfd, 0xa4, 0x13, 0xba, 0x7c, 0xbe, 0x38, 0xe8, 0xe2, 0x8f, 0x88, 0xe2,
	0x88, 0x98, 0xbf, 0x0c, 0xa1, 0xa7, 0xae, 0x64, 0xf7, 0x03, 0x66, 0x10, 0x99, 0x66, 0x6b, 0x8d,
	0x4c, 0xb3, 0x7f, 0x33, 0xda, 0xbf, 0x29, 0x25, 0x8c, 0xb5, 0x62, 0x15, 0xea, 0x26, 0x45, 0xf8,
	0xce, 0x6f, 0x0f, 0x90, 0xfe, 0xcf, 0x25, 0xfe, 0x5d, 0xab, 0x38, 0xbc, 0xc7, 0xe2, 0x37, 0x00,
	0x00, 0xff, 0xff, 0xbb, 0x2e, 0xfa, 0xb9, 0xb5, 0x01, 0x00, 0x00,
}
